'use strict';
const $=id=>document.getElementById(id);
let csrf='', config, library=[], reports=[], selected=[null,null], loading=0;
const names={cycle_s:'单件周期',x_m:'X 位置',y_m:'Y 位置',z_m:'Z 高度'};
const format=(value,digits=3)=>typeof value==='number'&&Number.isFinite(value)?value.toFixed(digits):'—';
function message(text){$('message').textContent=text;$('message').hidden=false;}
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':csrf},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
function option(select,value,text){const el=document.createElement('option');el.value=value;el.textContent=text;select.append(el);}
function safeAction(form,action){form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await action();}catch(error){message(error.message);}finally{button.disabled=false;}});}
async function refresh(){config=await api('lab/config');[library,reports]=await Promise.all([api('lab/datasets'),api('lab/reports')]);$('data-count').textContent=library.length+' 组数据';$('native-source').replaceChildren();option($('native-source'),'','选择一次已结束运行');config.candidates.forEach(r=>option($('native-source'),r.id,r.name));const ids=[$('base').value,$('observed').value];['base','observed'].forEach((key,i)=>{$(key).replaceChildren();option($(key),'','选择数据集');library.forEach(r=>option($(key),r.id,r.name+' · '+r.kind_label));$(key).value=library.some(r=>r.id===ids[i])?ids[i]:'';});renderLibrary();renderReports();}
function renderLibrary(){const query=$('search').value.toLowerCase();$('datasets').replaceChildren();const rows=library.filter(r=>(r.name+r.kind_label).toLowerCase().includes(query));if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent=library.length?'没有匹配的数据集':'实验库为空。从已有运行导入完整采样，或使用 CSV 接入日志。';tr.append(td);$('datasets').append(tr);return;}rows.forEach(r=>{const tr=document.createElement('tr');const td=document.createElement('td');td.textContent=r.name;const hash=document.createElement('small');hash.textContent='SHA-256 '+r.sha256.slice(0,16)+'…';td.append(hash);tr.append(td);[r.kind_label,r.count,format(r.duration_s,2)+' s'].forEach(v=>{const cell=document.createElement('td');cell.textContent=v;tr.append(cell);});const actions=document.createElement('td');for(const [key,label] of [['base','设为基准'],['observed','设为对照']]){const b=document.createElement('button');b.className='button secondary';b.textContent=label;b.onclick=()=>{$(key).value=r.id;loadSelected().catch(e=>message(e.message));$('analysis').scrollIntoView({behavior:'smooth'});};actions.append(b);}const download=document.createElement('a');download.className='button secondary';download.textContent='下载';download.href='/api/lab/datasets/'+r.id+'/download';actions.append(download);tr.append(actions);$('datasets').append(tr);});}
function renderReports(){$('report-list').replaceChildren();if(!reports.length){$('report-list').textContent='尚无对照报告。完成计算后自动保存。';return;}reports.slice(0,20).forEach(r=>{const row=document.createElement('div');row.className='report-row';const text=document.createElement('div');text.textContent=r.base.name+' → '+r.observed.name;const detail=document.createElement('small');detail.textContent=r.observed.kind_label+' · RMSE '+format(r.metrics.rmse)+' '+r.metrics.unit+' · '+new Date(r.created).toLocaleString();text.append(detail);const a=document.createElement('a');a.className='button secondary';a.textContent='下载报告';a.href='/api/lab/reports/'+r.id+'/download';const view=document.createElement('button');view.className='secondary';view.textContent='查看结果';view.onclick=async()=>{try{$('base').value=r.base.id;$('observed').value=r.observed.id;if(config.domain==='wind'){$('offset').value=r.metrics.offset_s;$('max-gap').value=r.metrics.max_gap_s;$('frame-confirm').checked=true;}await loadSelected();renderResult(r);$('analysis').scrollIntoView({behavior:'smooth'});}catch(error){message(error.message);}};const actions=document.createElement('div');actions.append(view,a);row.append(text,actions);$('report-list').append(row);});}
async function loadSelected(){clearResult();const sequence=++loading;const ids=[$('base').value,$('observed').value];const data=await Promise.all(ids.map(id=>id?api('lab/datasets/'+id):null));if(sequence!==loading)return;selected=data;draw();showSample();$('plot-caption').textContent=data.filter(Boolean).map(r=>r.count+' 行'+(r.plot_sampled?'（图表抽样）':'')).join(' / ');$('source-note').textContent=data.filter(Boolean).map(r=>r.kind_label+(r.plot_sampled?' · 绘图抽样':'')).join(' / ');}
function canvasContext(id){const canvas=$(id),rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;const height=Number(canvas.getAttribute('height'))/(canvas.dataset.scaled?Number(canvas.dataset.ratio):1);canvas.width=Math.max(200,Math.round(rect.width*ratio));canvas.height=Math.round(height*ratio);canvas.dataset.scaled='1';canvas.dataset.ratio=ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);return [ctx,rect.width,height];}
function plot(id,pointFn,xlabel,ylabel){const [ctx,w,h]=canvasContext(id),styles=getComputedStyle(document.body),muted=styles.getPropertyValue('--muted'),line=styles.getPropertyValue('--line');ctx.clearRect(0,0,w,h);ctx.font='11px Microsoft YaHei';ctx.fillStyle=muted;const groups=selected.map((data,i)=>data?data.rows.map(row=>pointFn(row,i)).filter(p=>p.every(Number.isFinite)):[]);const all=groups.flat();if(!all.length){ctx.fillText('选择数据后，显示实际采样曲线',24,h/2);return;}let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;all.forEach(([x,y])=>{xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y);});if(xmax===xmin)xmax=xmin+1;if(ymax===ymin){ymin-=.5;ymax+=.5;}const pad={left:58,right:20,top:18,bottom:32};const px=x=>pad.left+(x-xmin)/(xmax-xmin)*(w-pad.left-pad.right),py=y=>h-pad.bottom-(y-ymin)/(ymax-ymin)*(h-pad.top-pad.bottom);for(let i=0;i<=4;i++){const y=pad.top+(h-pad.top-pad.bottom)*i/4;ctx.strokeStyle=line;ctx.beginPath();ctx.moveTo(pad.left,y);ctx.lineTo(w-pad.right,y);ctx.stroke();ctx.fillStyle=muted;ctx.fillText(format(ymax-(ymax-ymin)*i/4,2),4,y+4);}ctx.fillText(format(xmin,2),pad.left,h-10);ctx.fillText(format(xmax,2),w-pad.right-45,h-10);ctx.fillText(xlabel,w/2,h-10);ctx.fillText(ylabel,6,12);groups.forEach((points,i)=>{ctx.strokeStyle=styles.getPropertyValue(i?'--secondary':'--primary');ctx.lineWidth=2;ctx.beginPath();if(id==='spatial'&&config.domain==='ld'){points.forEach(([x,y])=>{ctx.moveTo(px(x)+3,py(y));ctx.arc(px(x),py(y),3,0,Math.PI*2);});}else{points.forEach(([x,y],index)=>index?ctx.lineTo(px(x),py(y)):ctx.moveTo(px(x),py(y)));}ctx.stroke();if(points.length===1){ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(px(points[0][0])-2,py(points[0][1])-2,4,4);}});if(id==='trace'){const progress=Number($('cursor').value)/1000;const x=pad.left+progress*(w-pad.left-pad.right);ctx.strokeStyle=muted;ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(x,pad.top);ctx.lineTo(x,h-pad.bottom);ctx.stroke();ctx.setLineDash([]);}}
function timeShift(index){return config.domain==='wind'&&index?(Number($('offset').value)||0):0;}
function draw(){if(!config)return;const field=$('signal').value;plot('trace',(r,i)=>[r.time_s+timeShift(i),r[field]===null?NaN:r[field]],'时间 / s',names[field]+' / '+(config.domain==='ld'?'s':'m'));if(config.domain==='wind')plot('spatial',r=>[r.x_m,r.y_m],'X / m','Y / m');else plot('spatial',r=>[r.route,r.cycle_s===null?NaN:r.cycle_s],'目标出口 0=A / 1=B','周期 / s');}
function showSample(){const all=selected.flatMap((data,i)=>data?data.rows.map(r=>r.time_s+timeShift(i)):[]);if(!all.length){$('sample-detail').textContent='尚未选择数据。先导入已有运行或 CSV 日志。';return;}const lo=Math.min(...all),hi=Math.max(...all),time=Number($('cursor').value)===1000?hi:lo+(hi-lo)*Number($('cursor').value)/1000;$('sample-detail').textContent=selected.map((data,i)=>{if(!data)return (i?'对照':'基准')+'：未选择';const target=time-timeShift(i);if(target<data.rows[0].time_s-1e-9||target>data.rows[data.rows.length-1].time_s+1e-9)return (i?'对照':'基准')+'：此时刻在采集范围之外';const row=data.rows.reduce((best,r)=>Math.abs(r.time_s-target)<Math.abs(best.time_s-target)?r:best,data.rows[0]);return (i?'对照':'基准')+' · '+data.name+' · '+Object.entries(row).map(([k,v])=>k+'='+ (typeof v==='number'?format(v):v)).join('  ');}).join('\n');}
function clearResult(){['rmse','mae','p95','matched'].forEach(key=>$(key).textContent='—');$('report-download').hidden=true;$('quality').textContent='选择已变化，请重新计算或打开历史报告。';}
function renderResult(report){const m=report.metrics;['rmse','mae','p95'].forEach(key=>$(key).textContent=format(m[key])+' '+m.unit);$('matched').textContent=m.count+(config.domain==='ld'?' 件':' 点');$('result-method').textContent=report.method;$('quality').textContent=config.domain==='ld'?'配对物料 '+m.matched_jobs+' 件\n未配对：基准 '+m.unmatched_base+' / 对照 '+m.unmatched_observed+'\n出口不一致 '+m.route_mismatches+' · 结果不一致 '+m.outcome_mismatches+'\n重复编号 '+m.duplicate_jobs:'有效覆盖 '+format(m.coverage*100,1)+'%\n排除采样 '+m.skipped_samples+' 点\n时间偏移 '+m.offset_s+' s\n轴向偏差 X/Y/Z：'+Object.values(m.axis_bias).map(x=>format(x)).join(' / ')+' m';$('report-download').href='/api/lab/reports/'+report.id+'/download';$('report-download').hidden=false;}
safeAction($('compare-form'),async()=>{if(config.domain==='wind'&&!$('frame-confirm').checked)throw Error('请先核对轨迹坐标原点、轴向和单位');const report=await api('lab/compare',{base:$('base').value,observed:$('observed').value,offset_s:Number($('offset').value),max_gap_s:Number($('max-gap').value),frame_confirmed:$('frame-confirm').checked});renderResult(report);message('对照已保存，可在下方报告列表重新下载。');await refresh();});
safeAction($('native-form'),async()=>{await api('lab/native',{source_id:$('native-source').value,name:$('native-name').value});message('完整采样已进入个人实验库。请在下方设为基准或对照。');await refresh();});
safeAction($('import-form'),async()=>{const result=await api('lab/import',{name:$('import-name').value,kind:$('kind').value,csv:$('csv-text').value,frame:config.domain==='wind'?$('frame').value:'ENU',note:$('import-note').value});message('已保存 '+result.count+' 行，来源：'+result.kind_label+'。');await refresh();});
$('csv-file').addEventListener('change',async()=>{const file=$('csv-file').files[0];if(!file)return;if(file.size>750000){message('CSV 文件最多750 KB');return;}$('csv-text').value=await file.text();if(!$('import-name').value)$('import-name').value=file.name.replace(/\.csv$/i,'').slice(0,80);});
$('template').onclick=()=>{$('kind').value='demo';$('import-name').value='接口演示样例';$('csv-text').value=config.domain==='ld'?'time_s,job_id,cycle_s,route,outcome\n1.2,1,1.2,0,completed\n2.7,2,1.5,1,completed\n4,3,1.3,1,completed\n':'time_s,x_m,y_m,z_m\n0,0,0,0\n0.5,1,0.2,0.5\n1,2,0.4,1\n1.5,3,0.6,1.5\n';$('frame').value='ENU';message('已填入接口演示数据。保存后会持续保留演示来源标注。');};
$('refresh').onclick=()=>refresh().catch(e=>message(e.message));$('search').addEventListener('input',renderLibrary);['base','observed'].forEach(id=>$(id).addEventListener('change',()=>loadSelected().catch(e=>message(e.message))));$('signal').addEventListener('change',draw);$('cursor').addEventListener('input',()=>{draw();showSample();});window.addEventListener('resize',draw);['offset','max-gap'].forEach(id=>$(id).addEventListener('input',()=>{clearResult();draw();showSample();}));
(async()=>{try{const account=await api('account');csrf=account.csrf;await refresh();document.body.dataset.domain=config.domain;$('lab-brand').textContent=config.title;$('domain-description').textContent=config.domain==='ld'?'把 STM32 的单件执行结果，与同一物料的仿真记录放在一起核对。':'把仿真轨迹与实测位置放在同一时间轴，核对误差与有效覆盖范围。';$('native-hint').textContent=config.domain==='ld'?'先断开设备封存会话，再导入串口记录。仿真运行结束后可直接导入。':'从你的巡检任务导入完整轨迹；飞控日志先转换成下方 CSV 格式。';$('csv-schema').textContent='表头：'+config.columns.join(',')+'；时间单位秒。'+(config.domain==='ld'?'周期单位秒，出口0/1，结果completed/unknown。':'位置单位米；NED 自动转换成 ENU。');$('wind-options').hidden=config.domain!=='wind';$('frame-label').hidden=config.domain!=='wind';$('secondary-title').textContent=config.domain==='ld'?'出口与单件周期':'水平轨迹对照（局部坐标）';$('unit-note').textContent=config.domain==='ld'?'秒 / 单件':'米 / 局部位置';$('signal').replaceChildren();(config.domain==='ld'?['cycle_s']:['x_m','y_m','z_m']).forEach(field=>option($('signal'),field,names[field]));draw();}catch(error){message(error.message);}})();
