'use strict';
const ld = {
  data:null, user:null, csrf:'', page:'overview', view:'board', filter:'', archived:false,
  config:null, preset:'', selectedRun:null, poll:null, live:null, searchTimer:null,
  detail:null, focusBefore:null, toastTimer:null, busy:false
};
const el = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const labels = {overview:'工作区总览',run:'运行与调度',plans:'实验计划',datasets:'数据与对照',devices:'设备与校准',reports:'报告中心',favorites:'我的收藏',notices:'通知',settings:'设置',help:'使用帮助',assets:'资产与缺陷'};
const activityNames={created:'新建记录',prepared:'核对实验参数',run_requested:'请求运行',run_attached:'绑定运行结果',run_finished:'运行结束，等待复核',run_failed:'运行请求未完成',run_unresolved:'运行结果待人工关联',reference_attached:'关联实验资料',review_completed:'完成复核归档',archive_changed:'调整归档状态',calibrated:'保存校准观测'};
const sourceNames={simulation:'原生仿真',hardware:'本机实物',demo:'演示数据',measured_import:'实测导入 · 用户标注',simulation_import:'仿真导入 · 用户标注'};
function date(value, full=false){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?esc(value):d.toLocaleString('zh-CN',full?{}:{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function num(v,d=2){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';}
function button(label,action,value='',type='secondary',extra=''){return `<button class="btn ${type}" data-action="${action}" data-value="${esc(value)}" ${extra}>${label}</button>`;}
function empty(title,message,cta=''){return `<div class="empty"><div class="empty-icon">${icon('folder-open')}</div><h3>${title}</h3><p>${message}</p>${cta}</div>`;}
function head(title,subtitle,actions=''){return `<div class="page-head"><div><div class="eyebrow">${ld.data.domain==='ld'?'LD-FLEX / EXPERIMENT WORKSPACE':'WIND PATROL / ENGINEERING WORKSPACE'}</div><h1>${title}</h1><p class="sub">${subtitle}</p></div><div class="actions">${actions}</div></div>`;}
const runStates={running:'运行中',completed:'完成',stopped:'已停止',failed:'运行失败',interrupted:'中断待检查',DONE:'完成',ABORTED:'安全中止',TIMEOUT:'时长耗尽',MANUAL:'手控中',STOPPED:'手控结束'};
function runLabel(value){return runStates[value]||value;}
function runPill(value){return `<span class="pill ${esc(value)}">${esc(runLabel(value))}</span>`;}
const workflowStates={pending:'待复核',confirmed:'已确认',assigned:'已派单',resolved:'已处理待验收',rejected:'已驳回',closed:'已关闭'};
function calibrationPill(c){return `<span class="pill ${c.passed?'ready':'review'}">${c.passed?'偏差合格':'偏差超限'}</span>`;}
function pill(value){return `<span class="pill ${esc(value)}">${esc(ld.data.states[value]||sourceNames[value]||value)}</span>`;}
function field(name,label,type='text',value='',attrs=''){return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;}
function select(name,label,options,value='',attrs=''){return `<label class="field"><span>${label}</span><select name="${name}" ${attrs}>${options.map(([v,n])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;}
function textarea(name,label,value='',attrs=''){return `<label class="field"><span>${label}</span><textarea name="${name}" ${attrs}>${esc(value)}</textarea></label>`;}
function formWrap(body,label='保存'){return `<form id="modal-form"><div class="error" role="alert" id="form-error" hidden></div>${body}<div class="form-actions">${button('取消','close')}<button class="btn" type="submit">${label}</button></div></form>`;}
function icons(){window.lucide.createIcons();}
function toast(message,error=false){const box=el('toast');box.textContent=message;box.hidden=false;box.setAttribute('role',error?'alert':'status');clearTimeout(ld.toastTimer);ld.toastTimer=setTimeout(()=>box.hidden=true,6000);}
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':ld.csrf},body:JSON.stringify(body)});if(response.status===401){location.replace('/login.html?next='+encodeURIComponent(location.pathname+location.hash));throw Error('请重新登录');}const result=await response.json();if(!response.ok)throw Error(result.error||'请求未完成');return result;}
async function refresh(renderPage=true){ld.data=await api('studio/bootstrap');applyPreferences();shell();if(renderPage)render();}
function applyPreferences(){document.title=(ld.data.domain==='wind'?'风巡智航':'LD-Flex')+' · 实验工作区';document.body.dataset.domain=ld.data.domain;document.body.dataset.theme=ld.data.preferences.theme;document.body.dataset.density=ld.data.preferences.density;}
function shell(){const wind=ld.data.domain==='wind';el('brand-name').textContent=wind?'风巡智航':'LD-Flex';el('brand-mark').textContent=wind?'W':'LD';el('brand-subtitle').textContent=wind?'巡检仿真与实验协同':'分拣仿真与设备协同';el('user-name').textContent=ld.user.display_name;el('user-name').parentElement.setAttribute('aria-label','个人设置 · '+ld.user.display_name);el('avatar').textContent=ld.user.display_name.slice(0,1).toUpperCase();el('footer-title').textContent=`${wind?'风巡智航':'LD-Flex'} · V${ld.data.version}`;el('runtime-label').textContent=`${ld.data.mode==='local'?'本机服务':'在线服务'} · V${ld.data.version}`;
 const nav=[['overview','layout-dashboard'],['run','activity'],['plans','flask-conical'],['datasets','database'],['devices','cpu'],...(wind?[['assets','boxes']]:[]),['reports','file-chart-column'],['favorites','star'],['settings','settings-2']];
 el('nav').innerHTML=nav.map(([page,i])=>`<button data-action="navigate" data-page="${page}" aria-current="${ld.page===page?'page':'false'}">${icon(i)}${labels[page]}${page==='plans'&&ld.data.plans.filter(p=>p.state==='review'&&!p.archived).length?'<span class="badge">'+ld.data.plans.filter(p=>p.state==='review'&&!p.archived).length+'</span>':''}</button>`).join('');
 el('crumb').textContent=labels[ld.page]||labels.overview;el('notice-count').hidden=!ld.data.notices.length;el('notice-count').textContent=ld.data.notices.length;icons();}
function navigate(page){if(!labels[page])page='overview';ld.page=page;ld.filter='';location.hash=page;document.body.classList.remove('menu-open');shell();render();refresh(false).then(()=>{if(ld.page===page&&['overview','plans','devices','datasets','reports','notices'].includes(page))render();}).catch(error);}
function activePlans(){return ld.data.plans.filter(p=>p.archived===ld.archived&&(!ld.filter||(p.name+' '+p.objective).toLowerCase().includes(ld.filter.toLowerCase())));}
function findName(id){const r=[...ld.data.plans,...ld.data.devices,...ld.data.recipes].find(x=>x.id===id);return r?r.name:id.slice(0,10);}
function timeline(rows){return rows.length?`<div class="timeline">${rows.map(r=>`<div class="timeline-item"><span class="activity-icon">${icon(r.action==='calibrated'?'ruler':'git-commit-horizontal')}</span><div><strong>${activityNames[r.action]||esc(r.action)}</strong><small>${esc(findName(r.id))} · ${date(r.time)}</small></div></div>`).join('')}</div>`:empty('这里会记住你的操作','创建计划、执行实验和复核结果后，会显示真实的操作时间。');}
function stat(label,count,unit,note,i){return `<div class="stat"><div class="label">${icon(i)}${label}</div><strong>${count}<span class="unit">${unit}</span></strong><small>${note}</small></div>`;}
function planTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>实验 / 目的</th><th>状态</th><th>资料</th><th>更新于</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><button class="row-name" data-action="plan" data-value="${p.id}">${esc(p.name)}</button><span class="muted">${esc(p.objective)}</span></td><td>${pill(p.state)}</td><td>${p.references.length} 项</td><td>${date(p.updated)}</td><td><button class="icon-button" data-action="favorite" data-kind="plan" data-value="${p.id}" aria-label="收藏 ${esc(p.name)}">${icon(ld.data.preferences.favorites.includes('plan:'+p.id)?'star-off':'star')}</button></td></tr>`).join('')}</tbody></table></div>`:empty('你的下一次实验，从这里开始','先写清实验目的，再选择参数和设备。结果会跟着实验一起保存。',button(icon('plus')+' 新建实验','new-plan','',''));
}
function overview(){const plans=ld.data.plans.filter(p=>!p.archived);const reviews=plans.filter(p=>p.state==='review');const next=plans.find(p=>['ready','review','running'].includes(p.state));const used=ld.data.storage.used/ld.data.storage.limit*100;return head('工作区总览','计划、仿真、设备和结果，汇聚到同一个实验工作区。',button(icon('plus')+' 新建实验','new-plan','',''))+`<section class="hero"><div><div class="eyebrow">${next?'CONTINUE YOUR EXPERIMENT':'MAKE IT REPRODUCIBLE'}</div><h2>${next?esc(next.name):'从一个想法，到一次可复现的实验。'}</h2><p class="muted">${next?esc(next.objective):'选择场景，保存参数，在仿真结果与设备观测之间建立可核对的联系。'}</p><div class="actions">${next?button('继续实验 '+icon('arrow-right'),'plan',next.id,''):button('建立实验计划 '+icon('arrow-right'),'new-plan','','')}${button(icon('play')+' 快速运行','navigate','','secondary','data-page="run"')}</div></div><div class="journey"><span class="journey-step">${icon('clipboard-check')}参数核对</span>${icon('chevron-right')}<span class="journey-step">${icon('activity')}执行仿真</span>${icon('chevron-right')}<span class="journey-step">${icon('git-compare-arrows')}数据对照</span>${icon('chevron-right')}<span class="journey-step">${icon('archive')}复核归档</span></div></section><section class="stats">${stat('实验计划',plans.length,'项',plans.filter(p=>p.state==='completed').length+' 项已复核归档','flask-conical')}${stat('保存的运行',ld.data.runs.length,'次','参数与运行结果可下载','activity')}${stat('实验数据集',ld.data.datasets.length,'组',ld.data.datasets.filter(d=>d.kind==='hardware'||d.kind==='measured_import').length+' 组实物或实测标注','database')}${stat('待复核',reviews.length,'项',ld.data.reports.length+' 份数据对照报告','clipboard-check')}</section><div class="grid"><div class="stack"><section class="panel"><div class="panel-head"><h2>近期实验</h2>${button('查看全部 '+icon('arrow-up-right'),'navigate','','text','data-page="plans"')}</div>${planTable(plans.slice(0,5))}<div class="panel-foot"><span>参数、数据与结论随实验保存</span><span>${plans.length} 项实验</span></div></section><section class="panel"><div class="panel-head"><h2>最近保存的运行</h2>${button('运行中心','navigate','','text','data-page="run"')}</div>${runTable(ld.data.runs.slice(0,4))}</section></div><div class="stack"><section class="panel"><div class="panel-head"><h2>工作区动态</h2><span class="pill">实际操作记录</span></div>${timeline(ld.data.activity.slice(0,5))}</section><section class="panel panel-pad"><h2>工作区状态</h2><div class="health-row"><span>服务</span><span class="pill ready">在线 · ${esc(ld.data.runtime.os)}</span></div><div class="health-row"><span>我的数据容量</span><strong>${num(ld.data.storage.used/1024/1024,1)} / ${num(ld.data.storage.limit/1024/1024,0)} MB</strong></div><div class="meter"><progress max="100" value="${Math.min(100,used)}" aria-label="工作区容量"></progress></div><div class="health-row"><span>设备档案</span><span>${ld.data.devices.filter(p=>!p.archived).length} 台</span></div><div class="sub">实物控制通过设备所在电脑的本地网关执行。</div>${button('管理设备 '+icon('arrow-right'),'navigate','','text','data-page="devices"')}</section></div></div>`;}
function plans(){const rows=activePlans();return head('实验计划','从核对参数到复核归档，每一步都有对应的运行和资料。',button(icon('plus')+' 新建实验','new-plan','',''))+`<div class="toolbar"><input id="plan-filter" aria-label="筛选实验" placeholder="按实验名称或目的筛选" value="${esc(ld.filter)}"><label class="check"><input id="archived-filter" type="checkbox" ${ld.archived?'checked':''}>显示归档记录</label><div class="segmented">${['board','list'].map(v=>`<button data-action="plan-view" data-value="${v}" class="${ld.view===v?'active':''}">${v==='board'?'看板':'列表'}</button>`).join('')}</div></div><div id="plan-results">${ld.view==='list'?`<section class="panel">${planTable(rows)}</section>`:`<div class="board">${Object.entries(ld.data.states).map(([state,label])=>`<section class="board-column"><div class="board-heading"><span>${label}</span><span>${rows.filter(p=>p.state===state).length}</span></div>${rows.filter(p=>p.state===state).map(p=>`<article class="plan-card"><button data-action="plan" data-value="${p.id}">${esc(p.name)}</button><p>${esc(p.objective)}</p><div class="card-meta"><span class="priority ${p.priority}">${{high:'高优先级',normal:'常规',low:'低优先级'}[p.priority]}</span><span>${date(p.updated)}</span></div></article>`).join('')||'<p class="muted">暂无实验</p>'}</section>`).join('')}</div>`}</div>`;}
function runTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>运行</th><th>结果</th><th>来源</th><th>时间</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="row-name" data-action="run-detail" data-value="${esc(r.id)}">${esc(r.name)}</button><span class="source-id">${esc(r.id.slice(0,23))}</span></td><td>${runPill(r.status)}</td><td>${pill(r.kind)}</td><td>${date(r.created)}</td><td><a class="btn secondary small" href="${esc(r.url)}">${icon('download')}下载</a></td></tr>`).join('')}</tbody></table></div>`:empty('还没有保存的运行','运行一次场景，结果与参数会自动保存到当前账户。',button('选择运行场景','navigate','','secondary','data-page="run"'));}
function configFields(cfg=ld.config){const wind=ld.data.domain==='wind';const preset=ld.data.presets.find(p=>p.id===ld.preset)||ld.data.presets[0];let body=select('preset','运行场景',ld.data.presets.map(p=>[p.id,p.name]),ld.preset,'id="run-preset"')+`<p class="muted" id="preset-note">${esc(preset.description)}</p><div class="section-gap"></div>`;
 if(!wind)return body+select('task_kind','分拣任务',[['belt','双出口传送带'],['color','颜色识别 / 红蓝'],['size','尺寸分级 / 50mm'],['weight','称重分级 / 180g'],['barcode','扫码四出口 / 编号映射'],['rework','合格与重检分流']],cfg.task_kind||'belt')+select('policy','调度策略',[['BEAM','滚动窗口束搜索'],['GREEDY','单步贪心'],['EDD','最早交期 EDD'],['FIFO','先到先做 FIFO']],cfg.policy)+`<div class="two-col">${field('count','物料数量 / 件','number',cfg.count,'min="4" max="80" required')}${field('seed','随机种子','number',cfg.seed,'min="0" max="4294967295" required')}</div>`+select('speed','仿真计算速度',[[1,'1 ×'],[2,'2 ×'],[5,'5 ×'],[10,'10 ×']],cfg.speed);
 return body+field('name','运行名称','text',preset.name,'maxlength="80" required')+`<div class="two-col">${field('seed','随机种子','number',cfg.seed,'min="0" max="4294967295" required')}${field('duration','仿真时长上限 / s','number',cfg.duration,'min="0.01" max="1000" step="0.01" required')}${field('max_speed','目标速度上限 / m/s','number',cfg.max_speed,'min="0.1" max="20" step="0.1" required')}${field('gust_amplitude','阵风幅值 / m/s','number',cfg.gust_amplitude,'min="0" max="20" step="0.1" required')}</div><label class="check"><input name="adaptive_control" type="checkbox" ${cfg.adaptive_control?'checked':''}>启用风扰估计前馈与动态限速</label><details><summary>航线、风场与控制参数</summary><div class="section-gap"></div><div class="two-col">${field('wind_x','东向风 / m/s','number',cfg.wind[0],'step="0.1" required')}${field('wind_y','北向风 / m/s','number',cfg.wind[1],'step="0.1" required')}${field('kp','比例增益 Kp','number',cfg.kp,'step="0.01" min="0" max="10" required')}${field('kd','微分增益 Kd','number',cfg.kd,'step="0.01" min="0" max="10" required')}${field('dt','采样步长 / s','number',cfg.dt,'step="0.01" min="0.01" max="0.2" required')}${field('initial_battery','初始电量 / 0–1','number',cfg.initial_battery,'step="0.01" min="0" max="1" required')}</div>${textarea('waypoints','航点 / 每行 东,北,高度（米）',cfg.waypoints.map(p=>p.join(',')).join('\n'),'required')}<p class="muted">采用局部 ENU 坐标，起点为 (0,0,0)。航点需在围栏内且高度至少1米。</p></details>`;}
function readConfig(form){const f=new FormData(form);const wind=ld.data.domain==='wind';const cfg=structuredClone(ld.config);if(!wind){['count','seed','speed'].forEach(k=>cfg[k]=Number(f.get(k)));cfg.policy=f.get('policy');cfg.scenario=f.get('preset');cfg.task_kind=f.get('task_kind')||'belt';return cfg;}['seed','duration','max_speed','gust_amplitude','kp','kd','dt','initial_battery'].forEach(k=>cfg[k]=Number(f.get(k)));cfg.wind[0]=Number(f.get('wind_x'));cfg.wind[1]=Number(f.get('wind_y'));cfg.adaptive_control=f.get('adaptive_control')==='on';cfg.waypoints=String(f.get('waypoints')).trim().split(/\r?\n/).map(s=>s.split(',').map(x=>Number(x.trim())));if(cfg.waypoints.some(p=>p.length!==3||p.some(x=>!Number.isFinite(x))))throw Error('每行航点需要三个逗号分隔的有限数值');return cfg;}
function runPage(){return head(ld.data.domain==='ld'?'分拣仿真与手控':'无人机仿真与手控','每次运行自动播放三维动画；原始参数、事件与结果随运行保存。',button(icon('git-compare-arrows')+' 配对基准实验','benchmark')+button(icon('panel-top')+' 专业控制台','classic'))+`<div class="run-layout"><div class="stack"><section id="scene3d" aria-label="三维仿真播放器"></section><section class="panel"><div class="panel-head"><h2>保存的参数模板</h2>${button('保存当前参数','save-recipe')}</div><div class="panel-pad" id="recipe-shortcuts">${ld.data.recipes.filter(p=>!p.archived).map(r=>button(esc(r.name),'use-recipe',r.id,'secondary small')).join(' ')||'<p class="muted">保存一组常用参数，下一次运行直接复用。</p>'}</div></section></div><section class="panel panel-pad run-side"><h2>运行配置</h2><form id="run-form"><div class="section-gap"></div>${configFields()}<div class="error" id="run-error" role="alert" hidden></div><div class="actions"><button class="btn" id="run-submit" type="submit">${icon('play')}自动仿真</button>${ld.data.domain==='ld'?button('停止仿真','stop','','danger'):''}</div><div id="recovery-controls" hidden class="inline-note warning-note"><p>仿真故障锁定，检查当前未知结果。</p><label class="check"><input id="recovery-check" type="checkbox">已核对仿真通道并确认清空</label>${button('确认恢复仿真','recover')}</div></form>${button(icon('gamepad-2')+' 开始手控仿真','manual-start','','secondary manual-start')}${button('结束手控并保存','manual-stop','','danger manual-start')}<p class="sub section-gap">${ld.data.domain==='wind'?'手控支持键鼠、触屏和标准USB游戏手柄。遥控器经HID转换器接入后，可映射输入通道。':'自动分拣按场景属性选择出口；手控时由你选择出口并逐件上料。'} 手控只作用于当前仿真会话。</p></section></div><details class="panel run-secondary"><summary class="panel-head"><h2>${ld.data.domain==='ld'?'周期与原始信号':'航线与原始轨迹'}</h2><span id="live-status" class="pill">等待运行</span></summary><div class="chart-wrap"><canvas id="run-chart" class="chart" role="img" aria-label="实际运行数据图"></canvas></div><div id="run-metrics" class="panel-pad"></div><div class="panel-foot"><span>${ld.data.domain==='ld'?'原生控制状态机 / 10ms 步长':'完整三维回放 / 局部ENU米制'}</span><span id="chart-label">无运行数据</span></div></details><section class="panel section-gap"><div class="panel-head"><h2>运行记录 · 可再次播放三维动画</h2><span class="muted" id="run-history-count">${ld.data.runs.length} 次</span></div><div id="run-history">${runTable(ld.data.runs)}</div></section>`;}
function datasets(){const rows=ld.data.datasets.filter(r=>(r.name+' '+r.kind_label).toLowerCase().includes(ld.filter.toLowerCase()));return head('数据与对照','每组数据保留来源、采样数量和摘要。先核对数据来源，再计算误差。',button(icon('upload')+' 导入 CSV','import')+button(icon('git-compare-arrows')+' 数据对照','compare','',''))+`<div class="toolbar"><input id="dataset-filter" aria-label="筛选数据集" value="${esc(ld.filter)}" placeholder="按名称或来源筛选">${button('从已保存运行提取数据','native')}</div><section class="panel">${rows.length?`<div class="table-wrap"><table><thead><tr><th>数据集</th><th>来源</th><th>采样</th><th>时长 / s</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="row-name" data-action="dataset" data-value="${r.id}">${esc(r.name)}</button><span class="source-id">SHA256 ${esc(r.sha256.slice(0,16))}…</span></td><td>${pill(r.kind)}</td><td>${r.count} 行</td><td>${num(r.duration_s)}</td><td><a class="btn secondary small" href="/api/lab/datasets/${r.id}/download">${icon('download')}下载</a><button class="icon-button" data-action="favorite" data-value="${r.id}" data-kind="dataset" aria-label="收藏 ${esc(r.name)}">${icon('star')}</button></td></tr>`).join('')}</tbody></table></div>`:empty('建立你的实验数据集','可以从真实仿真记录提取，也可以导入按规定表头整理的实测 CSV。',button('从运行提取','native'))}</section><div class="inline-note">${ld.data.domain==='ld'?'物料编号用于配对；未知结果和出口不一致的物料会被排除。':'轨迹比较采用局部 ENU 米制坐标。导入 NED 时转换轴向，原点仍需人工核对。'}</div>`;}
function devices(){const rows=ld.data.devices.filter(p=>!p.archived);return head('设备与校准','记录设备身份、接口和观测校准。连接实物前先把参数核对清楚。',button(icon('plus')+' 新建设备档案','new-device','',''))+`<div class="inline-note">${ld.data.domain==='ld'?'STM32 分拣装置通过 USB 串口接入本机控制台；设备档案本身不会启动机械动作。':'当前支持飞行轨迹 CSV 导入和坐标核对。飞控型号确定后，扩展本地数据接口。'}</div><div class="device-grid">${rows.map(r=>{const c=r.calibrations.at(-1);return `<article class="device-card"><div class="device-top"><span class="device-icon">${icon(r.interface==='serial'?'cpu':r.interface==='csv'?'file-input':'monitor')}</span><span class="pill">${{serial:'USB 串口',csv:'CSV 数据',simulation:'仿真'}[r.interface]}</span></div><h3>${esc(r.name)}</h3><p class="muted">${esc(r.model||'型号待填')} · ${esc(r.serial||'未填资产编号')}</p><div class="health-row"><span>最近校准</span>${c?calibrationPill(c):'<span class="muted">尚无观测</span>'}</div><div class="sub">${c?esc(c.label)+' · 偏差 '+num(c.error)+' '+esc(c.unit):'现场测试后填入观测值'}</div><div class="actions">${button('查看档案','device',r.id)}${button(icon('ruler')+' 校准观测','calibrate',r.id,'text')}</div></article>`;}).join('')||`<section class="panel">${empty('先登记你的实验设备','型号、资产编号和接口随设备保存，校准观测可关联到实验报告。',button('新建设备档案','new-device','',''))}</section>`}</div><div class="section-gap actions">${ld.data.domain==='ld'?'<a class="btn secondary" href="/classic.html#hardware">'+icon('usb')+' 打开本机实物连接</a>':'<a class="btn secondary" href="/lab.html">'+icon('file-input')+' 轨迹信号详细回放</a>'}</div>`;}
function reports(){const plans=ld.data.plans.filter(p=>p.state==='completed');return head('报告中心','实验结论、原始运行和数据摘要可以一起导出，用于复核和分享。',`<a href="/api/account/export" class="btn secondary">${icon('download')}备份我的工作区</a>`)+`<div class="grid"><section class="panel"><div class="panel-head"><h2>实验归档报告</h2><span class="pill">${plans.length} 份</span></div>${plans.length?`<div class="panel-pad">${plans.map(p=>`<div class="source-row"><div><strong>${esc(p.name)}</strong><p class="muted">${date(p.updated)} · ${p.references.length} 项关联资料</p></div><div class="actions">${button('查看 / 打印','print',p.id,'secondary small')}<a class="btn secondary small" href="/api/studio/plans/${p.id}/download">${icon('download')}实验包</a></div></div>`).join('')}</div>`:empty('等待第一份完整实验报告','在实验详情查看运行，写下实际结论后归档。',button('查看实验计划','navigate','','secondary','data-page="plans"'))}</section><section class="panel"><div class="panel-head"><h2>数据对照报告</h2><span class="pill">${ld.data.reports.length} 份</span></div><div class="panel-pad">${ld.data.reports.map(r=>`<div class="source-row"><div><strong>${esc(r.base.name)} / ${esc(r.observed.name)}</strong><p class="muted">RMSE ${num(r.metrics.rmse,4)} ${esc(r.metrics.unit)} · ${r.metrics.count} 对</p></div>${button('查看','report',r.id,'secondary small')}</div>`).join('')||'<p class="muted">选择两组数据，完成对照后报告保存在这里。</p>'}</div></section></div>`;}
function notices(){return head('通知','来自实验状态、校准观测和工作区容量的实际提醒。')+`<section class="panel">${ld.data.notices.map(r=>`<article class="notice-card">${icon(r.level==='warning'?'triangle-alert':'clipboard-check')}<div><h3>${esc(r.name)}</h3><p>${esc(r.detail)}</p></div><div class="actions">${button('查看',r.kind==='settings'?'navigate':r.kind,r.target,'secondary small',r.kind==='settings'?'data-page="settings"':'')}${button('已知晓','dismiss',r.id,'text')}</div></article>`).join('')||empty('没有待处理提醒','实验完成待复核或设备校准需要检查时，提醒会出现在这里。')}</section>`;}
function settings(){return head('设置','外观、账户与数据备份，随个人工作区保存。')+`<section class="panel panel-pad"><form id="preferences-form"><div class="settings-grid"><div class="settings-label"><h2>工作区外观</h2><p>刷新页面和重新登录后保持一致。</p></div><div><div class="two-col">${select('theme','主题',[['light','浅色'],['dark','深色']],ld.data.preferences.theme)}${select('density','信息密度',[['comfortable','舒适'],['compact','紧凑']],ld.data.preferences.density)}</div><button class="btn" type="submit">保存外观设置</button></div></div></form></section><section class="panel panel-pad section-gap"><form id="profile-form"><div class="settings-grid"><div class="settings-label"><h2>个人资料</h2><p>只更新显示名称和邮箱。</p></div><div><div class="two-col">${field('display_name','显示名称','text',ld.user.display_name,'maxlength="40" required')}${field('email','邮箱（可留空）','email',ld.user.email||'','maxlength="254"')}</div><div class="actions"><button class="btn secondary" type="submit">更新个人资料</button><a class="btn text" href="/data.html">密码与原有数据管理</a></div></div></div></form></section><section class="panel panel-pad section-gap"><div class="settings-grid"><div class="settings-label"><h2>数据与运行环境</h2><p>备份包括你账户对应的数据。</p></div><div class="actions"><a class="btn secondary" href="/api/account/export">${icon('download')}下载完整备份</a>${button('退出登录','logout','','danger')}</div></div><dl class="runtime-table"><div><dt>软件版本</dt><dd>V${ld.data.version}</dd></div><div><dt>服务模式</dt><dd>${ld.data.mode==='local'?'本机服务':'在线服务'}</dd></div><div><dt>当前服务系统</dt><dd>${esc(ld.data.runtime.os)} / Python ${esc(ld.data.runtime.python)}</dd></div><div><dt>实物控制</dt><dd>${ld.data.hardware_allowed?'当前账户具备本机操作权限':ld.data.domain==='wind'?'轨迹文件导入':'需本机操作权限'}</dd></div></dl></section>`;}
function help(){return head('使用帮助','先完成一次实验，再逐步接入实物观测。')+`<section class="panel panel-pad"><h2>完成一次可复现的实验</h2><div class="timeline">${['在实验计划中新建实验，写清目的并选择参数。','核对参数后点击执行，软件保存真实仿真结果。','从已保存运行提取数据，导入观测 CSV 后计算对照误差。','在实验详情关联数据与报告，查看运行结果，填写结论并归档。','在报告中心下载实验包，包含参数、操作记录、运行文件和 SHA256 清单。'].map((s,i)=>`<div class="timeline-item"><span class="pill">0${i+1}</span><p class="muted">${s}</p></div>`).join('')}</div></section><section class="panel panel-pad section-gap"><h2>常见操作</h2>${[['为什么设备档案没有直接启动按钮？','设备登记用于管理身份和校准。真实机械动作必须在设备所在电脑、具备操作权限、确认通道和板载确认按钮后执行。'],['校准“通过”是什么含义？','表示你输入的观测值与参考值的绝对偏差未超过输入容差。它只对该测量项和单位成立，不能替代整机校准。'],['数据是不是其他用户也能看到？','数据按当前账户的工作区保存和访问。全局搜索、收藏、实验关联和下载也限定在你的账户。'],['可以适配哪些系统？','本轮采用浏览器界面、Python服务与本地设备接口的结构。当前系统显示在设置页；各系统安装包和串口驱动需分别验收，安装包等界面验收后制作。'],['专业控制台与这个工作区有什么关系？','专业控制台保留完整的控制参数、故障事件、时序和细节回放；两者读取同一账户的实际运行库。'],['快捷键','Ctrl / Cmd + K 打开全局搜索；Esc 关闭弹窗。']].map(([t,p])=>`<details class="faq"><summary>${t}</summary><p>${p}</p></details>`).join('')}</section>`;}
async function favoritesPage(){const rows=await api('studio/search');if(ld.page!=='favorites')return;const favs=rows.filter(r=>ld.data.preferences.favorites.includes(r.kind+':'+r.id));el('content').innerHTML=head('我的收藏','常用实验、设备和数据，随账户保存。')+`<section class="panel"><div class="panel-pad search-results">${searchRows(favs)||'<p class="muted">在实验或数据旁点击星标，快速回到常用资料。</p>'}</div></section>`;icons();}
function searchRows(rows){return rows.map(r=>`<button data-action="${r.kind==='recipe'?'use-recipe':r.kind==='run'?'run-detail':r.kind}" data-value="${esc(r.id)}">${icon({plan:'flask-conical',device:'cpu',recipe:'sliders-horizontal',run:'activity',dataset:'database',report:'file-chart-column'}[r.kind])}<span><strong>${esc(r.name)}</strong><span class="muted">${esc(r.description)}</span></span><span class="result-type">${esc(r.label)}</span></button>`).join('');}
function render(){clearInterval(ld.poll);clearInterval(ld.twinPoll);ld.twin?.dispose();ld.twin=null;const pages={overview,plans,run:runPage,datasets,devices,reports,notices,settings,help};if(ld.page==='favorites'){favoritesPage().catch(error);return;}if(ld.page==='assets'){assetsPage().catch(error);return;}el('content').innerHTML=(pages[ld.page]||overview)();icons();if(ld.page==='run'){bindRunForm();mountTwin().then(()=>loadInitialRun()).catch(error);if(ld.data.domain==='ld'){pollLive().catch(error);ld.poll=setInterval(()=>pollLive().catch(error),1600);}}}
function error(e){toast(e.message||String(e),true);}
function modal(title,html){ld.focusBefore=document.activeElement;el('modal-title').textContent=title;el('modal-body').innerHTML=html;icons();if(!el('modal').open)el('modal').showModal();}
function closeModal(){el('modal').close();ld.detail=null;if(ld.focusBefore?.isConnected)ld.focusBefore.focus();if(ld.data&&['overview','plans','devices','datasets','reports','settings','notices'].includes(ld.page))render();}
function modalSubmit(callback){el('modal-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('[type=submit]');submit.disabled=true;el('form-error').hidden=true;try{await callback(new FormData(form),form);}catch(e){el('form-error').textContent=e.message;el('form-error').hidden=false;}finally{submit.disabled=false;}});}
function updateRunPreset(selectEl,form){const preset=ld.data.presets.find(p=>p.id===selectEl.value);ld.config=structuredClone(preset.config);ld.preset=preset.id;const root=form.id==='run-form'?form:el('plan-config');if(form.id==='run-form'){form.innerHTML=`<div class="section-gap"></div>${configFields()}<div id="run-error" class="error" role="alert" hidden></div><div class="actions"><button class="btn" id="run-submit" type="submit">${icon('play')}运行仿真</button>${ld.data.domain==='ld'?button('停止仿真','stop','','danger'):''}</div><div id="recovery-controls" hidden class="inline-note warning-note"><label class="check"><input id="recovery-check" type="checkbox">已核对仿真通道并确认清空</label>${button('确认恢复仿真','recover')}</div>`;}else root.innerHTML=configFields();icons();}
function bindRunForm(){el('run-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const btn=el('run-submit');btn.disabled=true;const old=btn.innerHTML;btn.textContent='计算中…';el('run-error').hidden=true;try{const cfg=readConfig(form);ld.config=cfg;ld.followCurrent=ld.data.domain==='ld';ld.manual=false;ld.twin?.clearQueue();ld.twin?.enableManual(false);const r=await api(ld.data.domain==='ld'?'start':'run',ld.data.domain==='ld'?cfg:{name:new FormData(form).get('name'),config:cfg,visual_profile:ld.twin?.model||'inspection'});if(ld.data.domain==='wind'){ld.selectedRun=r;drawRun(r);await ld.twin?.load(r.id,{autoplay:true});await refresh(false);refreshRunHistory();}else{await pollLive();await ld.twin?.live();}toast('仿真已执行，三维动画按原始时序播放');}catch(e){el('run-error').textContent=e.message;el('run-error').hidden=false;}finally{btn.disabled=false;btn.innerHTML=old;icons();}});}
async function loadInitialRun(){if(ld.page!=='run')return;if(ld.requestedQueue){const queue=ld.requestedQueue;ld.requestedQueue=null;await ld.twin.runQueue(queue);return;}const manual=await api('twin/live');if(manual.run_id&&manual.live&&!ld.requestedRun){ld.followCurrent=true;ld.manual=manual.summary?.control_mode==='manual';ld.twin?.setData(manual,{autoplay:true,live:true});ld.twin?.enableManual(ld.manual);return;}ld.followCurrent=false;const record=ld.requestedRun?ld.data.runs.find(r=>r.id===ld.requestedRun):ld.data.runs.find(r=>r.kind==='simulation'&&r.status!=='running');ld.requestedRun=null;if(!record){drawEmpty();return;}if(ld.data.domain==='wind'){ld.selectedRun=await api('tasks/'+record.id);drawRun(ld.selectedRun);}else {const r=await api('run?id='+encodeURIComponent(record.id));drawRun(r,record);}await ld.twin?.load(record.id,{autoplay:!!ld.playRequested});ld.playRequested=false;}
async function pollLive(){if(ld.page!=='run'||ld.data.domain!=='ld')return;const state=await api('state');ld.live=state;const s=state.simulation;if(!s)return;el('live-status').textContent=s.status==='running'?'运行中 · '+s.controller.state:runLabel(s.status);el('recovery-controls').hidden=!s.awaiting_recovery;el('run-metrics').innerHTML=`<dl class="signal-metrics"><div><dt>确认完成</dt><dd>${s.summary.completed} / ${s.summary.total}</dd></div><div><dt>未知结果</dt><dd>${s.summary.unknown}</dd></div><div><dt>虚拟时间 / s</dt><dd>${num(s.virtual_s)}</dd></div></dl>`;el('chart-label').textContent='虚拟时间 '+num(s.virtual_s)+' s · '+s.controller.state;drawLD(s.results);if(s.status!=='running'&&(!ld.data.runs.some(r=>r.id===state.run_id)||ld.data.runs.some(r=>r.id===state.run_id&&r.status==='running'))){await refresh(false);refreshRunHistory();toast('仿真已结束，运行记录已保存');}}
function canvas(id){const c=el(id);if(!c)return null;const rect=c.getBoundingClientRect();const ratio=devicePixelRatio||1;c.width=Math.max(1,Math.floor(rect.width*ratio));c.height=Math.max(1,Math.floor(rect.height*ratio));const g=c.getContext('2d');g.scale(ratio,ratio);return {g,w:rect.width,h:rect.height,c};}
function chartBase(id='run-chart'){const box=canvas(id);if(!box)return;const {g,w,h}=box;g.font='11px Segoe UI';g.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');g.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');for(let i=0;i<5;i++){const y=25+(h-65)*i/4;g.beginPath();g.moveTo(45,y);g.lineTo(w-20,y);g.stroke();}return box;}
function drawEmpty(id='run-chart',label='运行后显示实际采样数据'){const box=chartBase(id);if(!box)return;box.g.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');box.g.textAlign='center';box.g.fillText(label,box.w/2,box.h/2);}
function drawLD(rows,id='run-chart'){if(!rows?.length){drawEmpty(id,'等待已完成或未知物料结果');return;}const box=chartBase(id);if(!box)return;const {g,w,h}=box;const vals=rows.map(r=>typeof r.finished==='number'?Math.max(0,r.finished-r.started):r.outcome==='completed'&&typeof r.uptime_end==='number'?((r.uptime_end-r.uptime_start)>>>0)/1000:0);const max=Math.max(...vals,.01)*1.2;const step=(w-75)/rows.length;rows.forEach((r,i)=>{const bh=(h-65)*vals[i]/max;g.fillStyle=r.outcome==='completed'?getComputedStyle(document.body).getPropertyValue('--accent'):'#c7954b';g.fillRect(46+i*step,h-40-bh,Math.max(2,step*.6),bh);if(rows.length<15){g.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');g.fillText(String(r.order_id),46+i*step,h-20);}});g.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');g.fillText('单件周期 / s',45,14);g.fillText(num(max),4,29);g.fillText('0',30,h-39);}
function drawPath(rows,id='run-chart',waypoints=[]){if(!rows?.length){drawEmpty(id);return;}const box=chartBase(id);if(!box)return;const {g,w,h}=box;const xs=rows.map(r=>r.x??r.x_m),ys=rows.map(r=>r.y??r.y_m);const allx=xs.concat(waypoints.map(p=>p[0])),ally=ys.concat(waypoints.map(p=>p[1]));const xmin=Math.min(...allx),ymin=Math.min(...ally),xmax=Math.max(...allx),ymax=Math.max(...ally);const scale=Math.min((w-95)/Math.max(xmax-xmin,1),(h-80)/Math.max(ymax-ymin,1));const px=x=>55+(x-xmin)*scale,py=y=>h-45-(y-ymin)*scale;g.strokeStyle=getComputedStyle(document.body).getPropertyValue('--accent');g.lineWidth=2;g.beginPath();rows.forEach((r,i)=>{const x=px(xs[i]),y=py(ys[i]);if(i)g.lineTo(x,y);else g.moveTo(x,y);});g.stroke();waypoints.forEach((p,i)=>{g.fillStyle='#a27831';g.beginPath();g.arc(px(p[0]),py(p[1]),4,0,Math.PI*2);g.fill();g.fillText('WP'+(i+1),px(p[0])+7,py(p[1])-5);});g.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');g.fillText('北向 / m',12,14);g.fillText('东向 / m',w-76,h-12);g.fillText(num(xmin,1),45,h-24);g.fillText(num(xmax,1),px(xmax)-12,h-24);}
function drawRun(r,record){if(!el('run-chart'))return;if(ld.data.domain==='wind'){drawPath(r.samples,'run-chart',r.config.waypoints);el('live-status').textContent=runLabel(r.summary.status);el('chart-label').textContent= r.name+' · '+r.samples.length+' 个绘图采样';el('run-metrics').innerHTML=`<dl class="signal-metrics"><div><dt>航点完成</dt><dd>${r.summary.visited??'—'}</dd></div><div><dt>路径长度 / m</dt><dd>${num(r.metrics.path_length_m)}</dd></div><div><dt>观测可用率</dt><dd>${num(r.metrics.sensor_availability*100,1)}%</dd></div></dl>`;}else{const rows=r.events.filter(e=>e.kind==='job_result').map(e=>e.data);drawLD(rows);el('live-status').textContent=runLabel(record?.status||'已保存');el('chart-label').textContent='已完成 '+rows.filter(x=>x.outcome==='completed').length+' / '+rows.length+' 次派发';el('run-metrics').innerHTML=`<dl class="signal-metrics"><div><dt>完成</dt><dd>${rows.filter(x=>x.outcome==='completed').length}</dd></div><div><dt>未知</dt><dd>${rows.filter(x=>x.outcome==='unknown').length}</dd></div><div><dt>事件校验</dt><dd>${r.verification.ok?'通过':'未通过'}</dd></div></dl>`;}}
async function newPlan(){ld.config=structuredClone(ld.data.presets[0].config);ld.preset=ld.data.presets[0].id;modal('新建实验计划',formWrap(`<div class="two-col">${field('plan_name','实验名称','text','','maxlength="80" required placeholder="例如：阵风补偿效果验证"')}${select('priority','优先级',[['normal','常规'],['high','高'],['low','低']],'normal')}</div>${textarea('objective','实验目的','','maxlength="1000" required placeholder="要验证什么，如何判断结果？"')}${select('device_id','关联设备（可选）',[['','暂不关联'],...ld.data.devices.filter(d=>!d.archived).map(d=>[d.id,d.name])])}<details open><summary>选择运行参数</summary><div id="plan-config" class="section-gap">${configFields()}</div></details>`,'创建实验'));
 modalSubmit(async(f,form)=>{const p=await api('studio/plans',{name:f.get('plan_name'),objective:f.get('objective'),priority:f.get('priority'),device_id:f.get('device_id'),config:readConfig(form)});await refresh(false);await showPlan(p.id);toast('实验计划已保存');});}
async function showPlan(id){const result=await api('studio/plans/'+id);const p=result.plan;ld.detail=p;const index=Object.keys(ld.data.states).indexOf(p.state);const refs=p.references.map(r=>{const pool=r.kind==='run'?ld.data.runs:r.kind==='dataset'?ld.data.datasets:ld.data.reports;const item=pool.find(x=>x.id===r.id);return `<div class="source-row"><div><strong>${esc(item?.name||(item?.base?item.base.name+' / '+item.observed.name:r.id))}</strong><small class="muted">${{run:'运行结果',dataset:'实验数据',report:'对照报告'}[r.kind]}</small></div>${button('查看',r.kind==='run'?'run-detail':r.kind,r.id,'secondary small')}</div>`;}).join('');
 const operations=p.archived?button('恢复实验','archive',p.id,'secondary','data-collection="plans" data-archived="false"'):p.state==='draft'?`<label class="check"><input id="ready-confirm" type="checkbox">已核对实验目的、场景和参数</label>${button('确认参数','ready',p.id,'')}`:p.state==='ready'?button(icon('play')+' 执行仿真','start-plan',p.id,''):p.state==='running'?'<p class="muted">运行进行中，可在运行中心查看状态。故障需要人工核对与恢复。</p>':p.state==='review'?`<form id="complete-form">${textarea('conclusion','复核结论','','minlength="10" maxlength="4000" required placeholder="根据真实结果说明是否达到目的、异常和下一步。"')}<button type="submit" class="btn">保存结论并归档</button></form>`:`<h3>实验结论</h3><p class="sub">${esc(p.conclusion)}</p>`;
 modal(p.name,`<div class="detail-steps">${Object.entries(ld.data.states).map(([s,n],i)=>`<span class="${i<=index?'done':''}">${n}</span>`).join('')}</div><p class="muted">${esc(p.objective)}</p><div class="detail-meta section-gap"><div><small>状态</small><b>${p.archived?'归档记录 · ':''}${ld.data.states[p.state]}</b></div><div><small>关联设备</small><b>${esc(ld.data.devices.find(d=>d.id===p.device_id)?.name||'尚未关联')}</b></div><div><small>记录版本</small><b>${p.version} · ${date(p.updated)}</b></div></div>${operations}<div class="section-gap"><h3>关联资料</h3>${refs||'<p class="sub">执行后运行结果自动关联，也可以关联已有封存运行、数据和报告。</p>'}${['ready','review'].includes(p.state)&&!p.archived?button(icon('link')+' 关联资料','attach',p.id,'text'):''}</div><details class="section-gap"><summary>完整运行参数</summary><pre>${esc(JSON.stringify(p.config,null,2))}</pre></details><details class="section-gap"><summary>操作时间线 · ${result.events.length} 条</summary>${timeline(result.events)}</details><div class="form-actions">${p.state!=='running'?`<a class="btn secondary" href="/api/studio/plans/${p.id}/download">${icon('download')}实验包</a>`:''}${p.state==='completed'?button('查看报告','print',p.id):''}${!p.archived&&p.state!=='running'?button('移至归档记录','archive',p.id,'text','data-collection="plans" data-archived="true"'):''}${button('关闭','close')}</div>`);
 if(el('complete-form'))el('complete-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await api('studio/plans/'+id+'/complete',{version:p.version,conclusion:new FormData(e.currentTarget).get('conclusion')});await refresh();await showPlan(id);toast('复核结论已保存');}catch(e){error(e);}finally{b.disabled=false;}});}
async function newDevice(){modal('新建设备档案',formWrap(`${field('name','设备名称','text','','maxlength="80" required')}<div class="two-col">${field('model','型号','text','','maxlength="80" placeholder="例如 STM32F103C8T6"')}${field('serial','资产编号','text','','maxlength="80"')}</div>${select('interface','数据接口',[['serial','USB 串口'],['csv','CSV 数据'],['simulation','纯仿真']],ld.data.domain==='ld'?'serial':'csv')}${textarea('note','接线与设备备注','','maxlength="2000"')}`));modalSubmit(async f=>{await api('studio/devices',Object.fromEntries(f));closeModal();await refresh();toast('设备档案已保存');});}
async function showDevice(id){const r=ld.data.devices.find(d=>d.id===id);if(!r)throw Error('设备不存在');modal(r.name,`<div class="detail-meta"><div><small>型号</small><b>${esc(r.model||'待填')}</b></div><div><small>资产编号</small><b>${esc(r.serial||'待填')}</b></div><div><small>接口</small><b>${esc(r.interface)}</b></div></div><p class="muted">${esc(r.note)}</p><h3 class="section-gap">校准观测</h3>${r.calibrations.length?`<div class="table-wrap"><table><thead><tr><th>测量项</th><th>参考 / 观测</th><th>偏差 / 容差</th><th>结果</th><th>来源 / 有效期</th></tr></thead><tbody>${r.calibrations.toReversed().map(c=>`<tr><td>${esc(c.label)} / ${esc(c.unit)}</td><td>${num(c.reference)} / ${num(c.observed)}</td><td>${num(c.error)} / ±${num(c.tolerance)}</td><td><span class="pill ${c.passed?'ready':'review'}">${c.passed?'偏差合格':'偏差超限'}</span></td><td>${c.source==='demo'?'演示':'用户记录的现场观测'}<br>${esc(c.expires||'未指定有效期')}</td></tr>`).join('')}</tbody></table></div>`:empty('尚无校准观测','在硬件测试后按同一测量项、单位和参考值录入。')}<div class="form-actions">${button('新增校准观测','calibrate',id,'')}${button('收藏','favorite',id,'secondary','data-kind="device"')}${button('关闭','close')}</div>`);}
async function calibrateDevice(id){const r=ld.data.devices.find(d=>d.id===id);modal('校准观测 · '+r.name,formWrap(`<div class="two-col">${field('label','测量项','text','','maxlength="80" required placeholder="如 A 路通行周期"')}${field('unit','单位','text',ld.data.domain==='ld'?'s':'m','maxlength="20" required')}</div><div class="two-col">${field('reference','参考值','number','','step="any" required')}${field('observed','观测值','number','','step="any" required')}${field('tolerance','允许绝对偏差','number','','min="0" step="any" required')}${field('expires','有效期（可选）','date','')}</div>${select('source','观测来源',[['measured','用户记录的现场观测'],['demo','演示数据']],'measured')}${textarea('note','测量条件与备注','','maxlength="1000"')}<p class="muted">仅以本测量项的偏差和容差计算结果，不自动修改硬件参数。</p>`));modalSubmit(async f=>{const raw=Object.fromEntries(f);['reference','observed','tolerance'].forEach(k=>raw[k]=Number(raw[k]));raw.version=r.version;await api('studio/devices/'+id+'/calibrate',raw);await refresh(false);await showDevice(id);toast('校准观测已保存');});}
async function saveRecipe(){const form=el('run-form');if(!form)throw Error('请先在运行中心配置参数');const cfg=readConfig(form);modal('保存参数模板',formWrap(field('name','模板名称','text','','maxlength="80" required')));modalSubmit(async f=>{await api('studio/recipes',{name:f.get('name'),config:cfg});closeModal();await refresh();toast('参数模板已保存');});}
async function nativeDataset(){const c=await api('lab/config');modal('从运行提取实验数据',formWrap(`${select('source_id','已封存运行',c.candidates.map(r=>[r.id,r.name]))}${field('name','数据集名称','text','','maxlength="80" required')}${textarea('note','备注','','maxlength="1000"')}<p class="muted">读取原始运行中的完整采样，不使用界面绘图抽样。未封存的记录不能导入。</p>`));modalSubmit(async f=>{await api('lab/native',Object.fromEntries(f));closeModal();await refresh();toast('已从运行记录提取完整数据');});}
async function importDataset(){const cols=ld.data.domain==='ld'?'time_s,job_id,cycle_s,route,outcome':'time_s,x_m,y_m,z_m';modal('导入实验 CSV',formWrap(`${field('name','数据集名称','text','','maxlength="80" required')}${select('kind','数据来源',[['measured_import','实测导入（用户标注）'],['simulation_import','仿真导入（用户标注）'],['demo','接口演示数据']],'measured_import')}${ld.data.domain==='wind'?select('frame','输入坐标系',[['ENU','ENU：东 / 北 / 天'],['NED','NED：北 / 东 / 地']],'ENU'):''}<label class="field"><span>CSV 文件 / UTF-8 / 最大750 KB</span><input name="file" type="file" accept=".csv,text/csv" required><small>表头：${cols}</small></label>${textarea('note','来源与测量备注','','maxlength="1000"')}`));modalSubmit(async(f,form)=>{const file=form.elements.file.files[0];if(!file||file.size>750000)throw Error('请选择750 KB以内的 CSV 文件');const csv=await file.text();await api('lab/import',{name:f.get('name'),kind:f.get('kind'),frame:f.get('frame')||'ENU',csv,note:f.get('note')});closeModal();await refresh();toast('数据集已导入');});}
async function showDataset(id){const r=await api('lab/datasets/'+id);modal(r.name,`<div class="detail-meta"><div><small>来源</small><b>${esc(r.kind_label)}</b></div><div><small>完整采样</small><b>${r.count} 行</b></div><div><small>时长</small><b>${num(r.duration_s)} s</b></div></div><canvas id="dataset-chart" class="chart" role="img" aria-label="数据集采样图"></canvas><div class="sub">${r.plot_sampled?'绘图已抽样；计算和下载保留全部数据。':'绘图显示完整采样。'}</div><p class="sub">${esc(r.note)}</p><details class="section-gap"><summary>来源与摘要</summary><pre>${esc(JSON.stringify({source_id:r.source_id,input_frame:r.input_frame,frame:r.frame,sha256:r.sha256,normalized_sha256:r.normalized_sha256,hash_basis:r.hash_basis},null,2))}</pre></details><div class="form-actions"><a href="/api/lab/datasets/${id}/download" class="btn secondary">${icon('download')}下载完整数据</a>${button('收藏','favorite',id,'secondary','data-kind="dataset"')}${button('关闭','close')}</div>`);if(ld.data.domain==='wind')drawPath(r.rows,'dataset-chart');else drawLD(r.rows.map(x=>({...x,order_id:x.job_id,started:0,finished:x.cycle_s||0})),'dataset-chart');}
async function compareData(){if(ld.data.datasets.length<2)throw Error('先建立两组不同的数据集');const opts=ld.data.datasets.map(d=>[d.id,d.name+' / '+d.kind_label]);modal('数据对照',formWrap(`<div class="two-col">${select('base','基准数据',opts,opts[0][0])}${select('observed','对照数据',opts,opts[1][0])}</div>${ld.data.domain==='wind'?`<div class="two-col">${field('offset_s','对照时间偏移 / s','number',0,'step="any" required')}${field('max_gap_s','最大插值间隔 / s','number',1,'step="any" min="0.001" max="60" required')}</div><label class="check"><input name="frame_confirmed" type="checkbox" required>已核对两组轨迹的原点、轴向和米制单位一致</label>`:'<p class="muted">按唯一物料编号与相同出口配对；只计算两侧均已确认完成的周期。</p>'}`,'计算并保存报告'));modalSubmit(async f=>{const raw=Object.fromEntries(f);if(ld.data.domain==='wind'){raw.offset_s=Number(raw.offset_s);raw.max_gap_s=Number(raw.max_gap_s);raw.frame_confirmed=raw.frame_confirmed==='on';}const r=await api('lab/compare',raw);await refresh(false);await showReport(r.id);toast('对照报告已保存');});}
async function showReport(id){const r=ld.data.reports.find(x=>x.id===id);if(!r)throw Error('报告不存在');modal('数据对照报告',`<p class="muted">${esc(r.base.name)} / ${esc(r.observed.name)}</p><div class="stats section-gap">${stat('RMSE',num(r.metrics.rmse,4),r.metrics.unit,'均方根误差','git-compare-arrows')}${stat('MAE',num(r.metrics.mae,4),r.metrics.unit,'平均绝对误差','ruler')}${stat('P95',num(r.metrics.p95,4),r.metrics.unit,'绝对误差95分位','chart-no-axes-column')}${stat('有效配对',r.metrics.count,'组','按方法排除无效数据','check-check')}</div><p class="muted">${esc(r.method)}</p><p class="sub">${esc(r.scope)}</p><details class="section-gap"><summary>完整指标与来源</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details><div class="form-actions"><a class="btn secondary" href="/api/lab/reports/${id}/download">${icon('download')}下载 JSON</a>${button('关闭','close')}</div>`);}
async function runDetail(id){const record=ld.data.runs.find(x=>x.id===id);if(record?.kind==='hardware'){location.href='/lab.html';return;}ld.followCurrent=false;ld.manual=false;ld.twin?.enableManual(false);ld.requestedRun=id;ld.playRequested=true;closeModal();if(ld.page==='run'){await ld.twin?.load(id,{autoplay:true});}else navigate('run');}
async function attachReference(id){const p=ld.detail;const options=[...ld.data.runs.filter(r=>r.status!=='running').map(r=>['run:'+r.id,'运行 / '+r.name]),...ld.data.datasets.map(r=>['dataset:'+r.id,'数据 / '+r.name]),...ld.data.reports.map(r=>['report:'+r.id,'报告 / '+r.base.name+' / '+r.observed.name])];if(!options.length)throw Error('尚无已保存资料，先完成一次仿真');modal('关联实验资料',formWrap(select('target','资料',options)));modalSubmit(async f=>{const value=f.get('target');const at=value.indexOf(':');await api('studio/plans/'+id+'/attach',{version:p.version,kind:value.slice(0,at),target:value.slice(at+1)});await refresh(false);await showPlan(id);toast('资料已关联');});}
async function printReport(id){const {plan:p,events}=await api('studio/plans/'+id);modal('实验报告',`<article class="report-print"><div class="eyebrow">${esc(ld.data.title)} / EXPERIMENT REPORT</div><h2>${esc(p.name)}</h2><p><strong>实验目的</strong><br>${esc(p.objective)}</p><p><strong>复核结论</strong><br>${esc(p.conclusion||'尚未复核')}</p><p>记录编号：${p.id}<br>创建：${date(p.created,true)}<br>更新：${date(p.updated,true)}<br>状态：${ld.data.states[p.state]}<br>关联资料：${p.references.length} 项</p><h3>运行参数</h3><pre>${esc(JSON.stringify(p.config,null,2))}</pre><h3>资料索引</h3><pre>${esc(JSON.stringify(p.references,null,2))}</pre><h3>操作时间线</h3>${timeline(events)}<p class="muted">数据来源见实验包。仿真、演示数据和用户导入的观测各自保留标注。</p></article><div class="form-actions no-print">${button(icon('printer')+' 打印 / 保存为 PDF','browser-print','','')}<a class="btn secondary" href="/api/studio/plans/${id}/download">${icon('download')}完整实验包</a>${button('关闭','close')}</div>`);}
async function benchmark(){const wind=ld.data.domain==='wind';modal('配对基准实验',formWrap(`${wind?textarea('seeds','随机种子 / 逗号分隔','42,43,44','required'):field('seeds','配对种子组数','number',ld.data.mode==='cloud'?5:10,'min="2" max="50" required')}${!wind?field('count','每组物料数','number',24,'min="4" max="80" required'):'<p class="muted">在相同风场与随机种子下，比较启用/关闭自适应控制。</p>'}`,'执行配对实验'));modalSubmit(async f=>{const raw=wind?{config:ld.config,seeds:String(f.get('seeds')).split(',').map(Number)}:{seeds:Number(f.get('seeds')),count:Number(f.get('count'))};const r=await api(wind?'comparisons':'benchmark',raw);if(wind){await refresh(false);showBenchmark(r);}else{modal('配对基准实验',`<p id="paired-progress" role="status">正在计算各策略，请稍候…</p><div class="form-actions">${button('关闭','close')}</div>`);clearInterval(ld.benchmarkPoll);ld.benchmarkPoll=setInterval(async()=>{try{const s=await api('state');const b=s.batch;if(el('paired-progress'))el('paired-progress').textContent='已计算 '+(b.done||0)+' / '+(b.total||0)+' 场';if(!b.running){clearInterval(ld.benchmarkPoll);ld.benchmarkPoll=null;if(b.error)throw Error(b.error);await refresh(false);showBenchmark(b.result?.report);}}catch(e){clearInterval(ld.benchmarkPoll);ld.benchmarkPoll=null;error(e);}},1000);}});}
function showBenchmark(report){if(!report)throw Error('对照报告未生成');ld.queue=report.pairs?report.pairs.flatMap(p=>['baseline','adaptive'].map(k=>({id:p[k].task_id,name:'种子 '+p.seed+' · '+(k==='adaptive'?'自适应':'基线')}))):report.runs.map(r=>({id:r.run_id,name:'种子 '+r.seed+' · '+r.policy}));modal('配对基准结果',`<p>${ld.queue.length} 场运行已保存。每场都可播放对应的三维动画。</p><div class="form-actions">${button('连续播放全部 3D','play-paired')}${button('关闭','close')}</div><div class="stack">${ld.queue.map(r=>`<div class="panel-pad">${button(esc(r.name)+' · 播放','run-detail',r.id,'secondary small')}</div>`).join('')}</div><details class="section-gap"><summary>完整统计与配对记录</summary><pre>${esc(JSON.stringify(report,null,2))}</pre></details>`);}
function refreshRunHistory(){if(el('run-history')){el('run-history').innerHTML=runTable(ld.data.runs);if(el('run-history-count'))el('run-history-count').textContent=ld.data.runs.length+' 次';icons();}}
async function assetsPage(){const w=await api('workflow');if(ld.page!=='assets')return;el('content').innerHTML=head('资产与缺陷','资产、巡检任务、复核和工单状态保持关联。',button(icon('plus')+' 新建资产','new-asset')+button('登记缺陷','new-defect','',''))+`<div class="stats">${stat('电网资产',w.assets.length,'项','编号唯一','boxes')}${stat('缺陷记录',w.defects.length,'项','需人工复核','triangle-alert')}${stat('待复核',w.defects.filter(r=>r.status==='pending').length,'项','确认或驳回','clipboard-check')}${stat('已关闭',w.defects.filter(r=>r.status==='closed').length,'项','完成验收','check-check')}</div><section class="panel"><div class="panel-head"><h2>缺陷与工单</h2><a class="btn text" href="/workbench.html">完整业务控制台 ${icon('arrow-up-right')}</a></div>${w.defects.length?`<div class="table-wrap"><table><thead><tr><th>缺陷</th><th>资产</th><th>等级</th><th>状态</th><th>操作</th></tr></thead><tbody>${w.defects.map(r=>`<tr><td>${esc(r.title)}</td><td>${esc(r.asset_code)}</td><td>${esc({low:'低',medium:'中',high:'高'}[r.severity]||r.severity)}</td><td>${esc(workflowStates[r.status]||r.status)}</td><td>${button('复核 / 流转','defect',r.id,'secondary small')}</td></tr>`).join('')}</tbody></table></div>`:empty('还没有缺陷记录','登记资产后，可关联一条真实保存的仿真任务填写待复核记录。')}</section><section class="panel section-gap"><div class="panel-head"><h2>资产清单</h2></div><div class="panel-pad">${w.assets.map(r=>`<div class="source-row"><strong>${esc(r.code)} · ${esc(r.name)}</strong><span class="muted">${esc(r.location)}</span></div>`).join('')||'<p class="muted">先登记资产编号和位置。</p>'}</div></section>`;ld.workflow=w;icons();}
function newAsset(){modal('新建电网资产',formWrap(`${field('code','资产编号','text','','maxlength="40" required')}${field('name','资产名称','text','','maxlength="80" required')}${field('location','位置说明','text','','maxlength="120" required')}`));modalSubmit(async f=>{await api('workflow/assets',Object.fromEntries(f));closeModal();await assetsPage();toast('资产已保存');});}
async function newDefect(){const w=ld.workflow;if(!w?.assets.length||!ld.data.runs.length)throw Error('请先登记资产并保存一次巡检仿真');modal('登记待复核缺陷',formWrap(`${select('asset_id','关联资产',w.assets.map(r=>[r.id,r.code+' / '+r.name]))}${select('task_id','关联巡检任务',ld.data.runs.map(r=>[r.id,r.name]))}${field('title','缺陷描述','text','','maxlength="120" required')}${select('severity','等级',[['low','低'],['medium','中'],['high','高']],'medium')}${textarea('reason','记录依据','','maxlength="1000" required')}`));modalSubmit(async f=>{await api('workflow/defects',Object.fromEntries(f));closeModal();await assetsPage();toast('缺陷已保存，等待人工复核');});}
async function defect(id){const r=ld.workflow.defects.find(x=>x.id===id);const choices={pending:[['confirm','确认'],['reject','驳回']],confirmed:[['dispatch','派单']],assigned:[['resolve','标记已处理']],resolved:[['accept','验收关闭'],['return','退回处理']],rejected:[['reopen','重新复核']],closed:[['reopen','重新复核']]}[r.status];modal(r.title,formWrap(`<p class="muted">资产 ${esc(r.asset_code)} · 当前 ${esc(workflowStates[r.status]||r.status)} · 版本 ${r.revision}</p><div class="section-gap"></div>${select('action','状态操作',choices)}${textarea('reason','依据与备注','','maxlength="1000" required')}`));modalSubmit(async f=>{await api('workflow/transition',{...Object.fromEntries(f),id,revision:r.revision});closeModal();await assetsPage();toast('状态和流转记录已保存');});}
async function openSearch(){modal('搜索工作区',`<label class="field"><span>实验、设备、运行、数据与报告</span><input id="global-search" type="search" placeholder="输入名称、编号或状态"></label><div class="search-results" id="search-results"></div>`);el('global-search').focus();const rows=await api('studio/search');el('search-results').innerHTML=searchRows(rows.slice(0,12))||'<p class="muted">还没有保存的记录。</p>';icons();}
async function action(b){const name=b.dataset.action,value=b.dataset.value||'';switch(name){case 'navigate':closeModal();navigate(b.dataset.page);break;case 'menu':document.body.classList.toggle('menu-open');break;case 'close':closeModal();break;case 'classic':location.href='/classic.html';break;case 'new-plan':await newPlan();break;case 'plan':await showPlan(value);break;case 'new-device':await newDevice();break;case 'device':await showDevice(value);break;case 'calibrate':await calibrateDevice(value);break;case 'search':await openSearch();break;case 'plan-view':ld.view=value;render();break;case 'save-recipe':await saveRecipe();break;case 'use-recipe':{const r=ld.data.recipes.find(x=>x.id===value);if(!r)throw Error('参数模板不存在');ld.config=structuredClone(r.config);ld.preset=ld.data.presets.find(p=>JSON.stringify(p.config)===JSON.stringify(r.config))?.id||(ld.data.domain==='ld'?r.config.scenario:ld.data.presets[0].id);closeModal();navigate('run');toast('已应用参数模板 '+r.name);break;}case 'native':await nativeDataset();break;case 'import':await importDataset();break;case 'dataset':await showDataset(value);break;case 'compare':await compareData();break;case 'report':await showReport(value);break;case 'run-detail':await runDetail(value);break;case 'attach':await attachReference(value);break;case 'print':await printReport(value);break;case 'browser-print':window.print();break;case 'benchmark':await benchmark();break;case 'play-paired':ld.followCurrent=false;ld.requestedQueue=ld.queue;closeModal();if(ld.page==='run'){await ld.twin.runQueue(ld.requestedQueue);ld.requestedQueue=null;}else navigate('run');break;case 'manual-start':await manualStart();break;case 'manual-stop':await manualStop();break;case 'new-asset':newAsset();break;case 'new-defect':await newDefect();break;case 'defect':await defect(value);break;
 case 'favorite':await api('studio/favorite',{kind:b.dataset.kind,id:value});await refresh(!el('modal').open);toast('收藏已更新');break;
 case 'dismiss':await api('studio/dismiss',{id:value});await refresh();toast('提醒已处理');break;
 case 'archive':{const p=ld.data[b.dataset.collection]?.find(x=>x.id===value)||ld.detail;await api('studio/'+b.dataset.collection+'/'+value+'/archive',{version:p.version,archived:b.dataset.archived==='true'});closeModal();await refresh();toast('归档状态已保存');break;}
 case 'ready':if(!el('ready-confirm').checked)throw Error('先核对并勾选参数确认');await api('studio/plans/'+value+'/ready',{version:ld.detail.version,confirmed:true});await refresh(false);await showPlan(value);toast('参数核对已保存');break;
 case 'start-plan':{const p=ld.detail;ld.config=structuredClone(p.config);const result=await api('studio/plans/'+value+'/start',{version:p.version});await refresh(false);ld.requestedRun=result.run_id;ld.playRequested=true;closeModal();ld.followCurrent=ld.data.domain==='ld';navigate('run');toast('实验已执行，三维动画已加载');break;}
 case 'stop':await api('stop',{});await pollLive();toast('仿真已停止');break;
 case 'recover':if(!el('recovery-check').checked)throw Error('请先勾选仿真通道核对');await api('recover',{confirmed:true});await pollLive();toast('仿真控制器已恢复');break;
 case 'logout':await api('account/logout',{});location.replace('/login.html');break;
 }}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();if(b.disabled)return;b.disabled=true;try{await action(b);}catch(e){error(e);}finally{if(b.isConnected)b.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.id==='run-preset')updateRunPreset(e.target,e.target.closest('form'));if(e.target.id==='archived-filter'){ld.archived=e.target.checked;render();}});
document.addEventListener('input',e=>{if(e.target.id==='plan-filter'||e.target.id==='dataset-filter'){ld.filter=e.target.value;const start=e.target.selectionStart;const id=e.target.id;render();el(id).focus();el(id).setSelectionRange(start,start);}if(e.target.id==='global-search'){const q=e.target.value;clearTimeout(ld.searchTimer);ld.searchTimer=setTimeout(async()=>{try{const rows=await api('studio/search?q='+encodeURIComponent(q));if(el('global-search')?.value!==q)return;el('search-results').innerHTML=searchRows(rows)||'<p class="muted">没有找到对应资料。</p>';icons();}catch(e){error(e);}},180);}});
document.addEventListener('submit',async e=>{if(!['preferences-form','profile-form'].includes(e.target.id))return;e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const raw=Object.fromEntries(new FormData(e.target));if(e.target.id==='preferences-form'){await api('studio/preferences',raw);await refresh();toast('外观设置已保存');}else{const r=await api('account/profile',raw);ld.user=r.user;await refresh();toast('个人资料已更新');}}catch(e){error(e);}finally{if(b.isConnected)b.disabled=false;}});
document.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS'&&e.target.open&&ld.page==='run'){if(ld.selectedRun)drawRun(ld.selectedRun);else if(ld.live?.simulation)drawLD(ld.live.simulation.results);}},true);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch().catch(error);}});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(p&&p!==ld.page)navigate(p);});
window.addEventListener('resize',()=>{if(ld.page==='run'){if(ld.data.domain==='ld'&&ld.live?.simulation)drawLD(ld.live.simulation.results);else if(ld.selectedRun)drawRun(ld.selectedRun);}});
el('modal').addEventListener('close',()=>{if(ld.focusBefore?.isConnected)ld.focusBefore.focus();});
(async()=>{try{const info=await api('account');if(!info.user){location.replace('/login.html?next=/');return;}ld.user=info.user;ld.csrf=info.csrf;await refresh(false);ld.config=structuredClone(ld.data.presets[0].config);ld.preset=ld.data.presets[0].id;ld.page=labels[location.hash.slice(1)]?location.hash.slice(1):'overview';shell();render();}catch(e){el('content').innerHTML=`<div class="error">${esc(e.message)}</div><a class="btn secondary" href="/">重新加载</a>`;}})();

async function mountTwin(){const host=el('scene3d');if(!host)return;const {TwinPlayer}=await import('/twin-viewer.js');if(ld.page!=='run'||!host.isConnected)return;ld.twin=new TwinPlayer(host,{domain:ld.data.domain,csrf:ld.csrf,onControl:raw=>api('manual/control',raw)});ld.twinPoll=setInterval(()=>{if(ld.page==='run'&&(ld.followCurrent||ld.manual))ld.twin?.live();},160);}
async function manualStart(){const form=el('run-form');if(!form)throw Error('请先进入运行中心');const config=readConfig(form);ld.config=config;const r=await api('manual/start',{config,name:'手控 / '+(new FormData(form).get('name')||'分拣实验'),profile:ld.twin?.model||'inspection'});ld.manual=true;ld.followCurrent=true;ld.twin?.clearQueue();ld.twin?.enableManual();await ld.twin?.live();toast('手控仿真已启动，点入场景后使用键盘或触屏操作');}
async function manualStop(){await api('manual/stop',{});await ld.twin?.live();ld.manual=false;ld.followCurrent=false;ld.twin?.enableManual(false);await refresh(false);refreshRunHistory();toast('手控会话已结束，结果已保存');}

window.addEventListener('pagehide',()=>{clearInterval(ld.poll);clearInterval(ld.twinPoll);ld.twin?.dispose();});

document.addEventListener('twin:manual-ended',()=>{ld.manual=false;ld.followCurrent=false;refresh(false).then(()=>{refreshRunHistory();}).catch(error);});
