import * as T from './three.module.js';
import {OrbitControls} from './twin-orbit.js';
import {aircraft,sorterScenes,makeConveyor,makeFlight,disposeScene} from './twin-models.js';
import {normalizeReplay,mergeFrames,atTime,clamp,stateNames} from './twin-timeline.js';

const text=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fixed=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
const label=code=>stateNames[code]||code;
export class TwinPlayer {
  constructor(host,{domain='ld',csrf='',onControl=null}={}) {
    this.host=host;this.domain=domain;this.csrf=csrf;this.onControl=onControl;
    this.data=null;this.time=0;this.speed=1;this.playing=false;this.followLive=true;
    this.cameraMode=domain==='wind'?'follow':'cinematic';this.model='inspection';this.sceneId='belt';this.disposed=false;this.manual=false;this.keys=new Set();this.pointer={x:0,y:0};this.gpEnabled=false;this.lastInput=0;this.recording=false;
    this.abort=new AbortController();this.stateText='等待运行';this.lastUI=0;this.liveBusy=false;
    this.buildUI();this.createRenderer();this.bind();this.readPreferences();this.loop(0);
  }
  buildUI(){const flight=this.domain==='wind';this.host.classList.add('twin-player');
    this.host.innerHTML=`<div class="twin-head"><div><span class="twin-eyebrow">${flight?'FLIGHT DIGITAL SCENE':'VIRTUAL SORTING LINE'} · 3D</span><h2>${flight?'飞行现场':'分拣产线'}</h2></div><span class="twin-source">仿真动画 · 原始时序</span></div>
      <div class="twin-stage" tabindex="0" aria-label="三维运行场景，可用鼠标旋转和缩放"><canvas class="twin-canvas" aria-label="${flight?'三维无人机运行场景':'三维传送带分拣场景'}"></canvas><canvas class="twin-fallback" hidden aria-label="兼容模式运行画面"></canvas>
      <div class="twin-hud"><span class="twin-live">等待运行</span><span class="twin-clock">00:00.00</span></div><div class="twin-scene-info"><strong class="twin-scene-name">${flight?'多旋翼无人机 · 电力巡检场景':'传送带 · 单件分流 · 光电确认'}</strong><span class="twin-run-id">选择参数后运行，场景将自动播放</span></div>
      <div class="twin-fallback-notice" hidden>当前浏览器使用兼容动画。启用浏览器硬件加速可显示完整三维模型。</div>
      <div class="twin-start-hint">${flight?'无人机、航点、风场和安全事件':'传送带、物料、分流机构和传感器'}<small>每次运行自动加载对应动画</small></div>
      <div class="twin-touch" hidden><div class="twin-stick" aria-label="触屏移动摇杆"><span></span></div>${flight?'<div class="twin-rise"><button data-twin="up" aria-label="手控上升">↑</button><button data-twin="down" aria-label="手控下降">↓</button></div>':'<div class="twin-feed"><button data-twin="feed-a">上料 A</button><button data-twin="feed-b">上料 B</button></div>'}</div></div>
      <div class="twin-controls"><button data-twin="play" aria-label="播放回放" title="播放 / 暂停画面">▶</button><button data-twin="restart" title="从头回放" aria-label="从头回放">↺</button><label class="twin-scrub"><input type="range" min="0" max="1" step="0.01" value="0" aria-label="回放时间"><span>0.00 / 0.00 s</span></label><select class="twin-speed" aria-label="回放速度"><option value="0.25">0.25 ×</option><option value="0.5">0.5 ×</option><option value="1" selected>1 ×</option><option value="2">2 ×</option><option value="4">4 ×</option></select><button data-twin="live" class="twin-follow" hidden>跟随实时</button><button data-twin="fullscreen" aria-label="全屏场景" title="全屏">⛶</button></div>
      <div class="twin-toolbar"><label>视角 <select class="twin-camera" aria-label="三维视角"><option value="cinematic">电影视角</option><option value="overview">全景</option><option value="follow">跟随</option><option value="top">俯视</option><option value="free">自由观察</option></select></label><label>${flight?'机型':'场景'} <select class="twin-model" aria-label="${flight?'无人机模型':'分拣场景模型'}">${flight?aircraft.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''):sorterScenes.map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label><button data-twin="shot">保存画面</button><button data-twin="record">录制动画</button><a class="twin-download" hidden>回放数据</a></div>
      <dl class="twin-values"></dl><div class="twin-events" aria-label="运行事件时间线"></div>
      <div class="twin-manual" hidden><div><b>手控仿真</b><span>${flight?'WASD 平移 · Q/E 升降 · J/L 朝向 · 松开回中':'A / B 选择出口 · 空格单件上料'}</span></div><div><label><input class="twin-gamepad" type="checkbox">USB 手柄 / HID 遥控器</label><button data-twin="mapping">通道设置</button><span class="twin-controller">键鼠 / 触屏可用</span></div></div><p class="twin-note">${flight?'位置、风速和事件来自原始仿真；机体朝向按运动估算。':'模型位移按控制时序映射；尺寸和机械参数可在实物测试后标定。'} 暂停与拖动时间轴控制画面。</p><p class="twin-error" hidden role="alert"></p>`;
    this.$=sel=>this.host.querySelector(sel);this.stage=this.$('.twin-stage');this.canvas=this.$('.twin-canvas');
    if(!flight){this.$('.twin-stick').hidden=true;this.$('.twin-model').disabled=true;this.$('.twin-model').title='模型与本次运行的分拣任务对应，请在运行配置中选择任务';}
  }
  createRenderer(){try{
    if(new URLSearchParams(location.search).get('compat')==='1')throw Error('selected compatibility renderer');
    this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
    this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.4;
    this.scene=new T.Scene();this.scene.background=new T.Color(0x10202d);this.scene.fog=new T.Fog(0x10202d,40,140);
    this.camera=new T.PerspectiveCamera(43,1,.02,600);this.scene.add(new T.HemisphereLight(0xccecff,0x243328,2));
    const sun=new T.DirectionalLight(0xffecda,3);sun.position.set(14,24,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=22;sun.shadow.camera.bottom=-22;sun.shadow.normalBias=.03;this.scene.add(sun);
    const rim=new T.DirectionalLight(0x40bcde,1.8);rim.position.set(-10,6,-12);this.scene.add(rim);
    this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=true;this.controls.maxPolarAngle=Math.PI*.48;this.controls.minDistance=2;this.controls.maxDistance=200;this.controls.addEventListener('start',()=>{this.cameraMode='free';this.$('.twin-camera').value='free';});
    this.rebuildModel();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.stage);this.resize();this.host.dataset.renderer='webgl';
  }catch(e){this.renderer?.dispose();this.renderer=null;this.activateFallback();}}
  activateFallback(){this.canvas.hidden=true;this.$('.twin-fallback').hidden=false;this.$('.twin-fallback-notice').hidden=false;this.host.dataset.renderer='canvas2d';this.resizeObserver?.disconnect();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.stage);this.resize();}
  resize(){const w=this.stage.clientWidth,h=this.stage.clientHeight;if(!w||!h)return;if(this.renderer){this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}else{const c=this.$('.twin-fallback');c.width=Math.floor(w*(devicePixelRatio||1));c.height=Math.floor(h*(devicePixelRatio||1));}}
  rebuildModel(){if(!this.renderer)return;if(this.modelObject){this.scene.remove(this.modelObject.group);disposeScene(this.modelObject.group);}
    // 地面随模型清理，一处 viewer 一套资源。
    for(const old of [...this.scene.children])if(old.type==='Group'){this.scene.remove(old);disposeScene(old);}
    this.modelObject=this.domain==='wind'?makeFlight(this.scene,this.data||{frames:[],config:{waypoints:[],obstacles:[],geofence:100}},this.model):makeConveyor(this.scene,this.sceneId);this.setCamera(this.cameraMode);}
  setCamera(mode){this.cameraMode=mode;if(!this.renderer)return;const m=this.modelObject;
    if(mode==='top'){this.camera.position.set(m.target.x,m.extent*1.3,m.target.z+.01);this.controls.target.copy(m.target);}
    else if(mode==='overview'||mode==='cinematic'){this.camera.position.set(...m.home);this.controls.target.copy(m.target);}
    this.controls.update();}
  setData(raw,{autoplay=true,live=false}={}){if(this.disposed)return;const next=normalizeReplay(raw),changed=this.data?.run_id!==next.run_id;
    if(changed){this.time=0;this.followLive=live;this.playing=autoplay;this.$('.twin-start-hint').hidden=!!next.frames.length;}
    const wasLive=this.data?.live;
    if(!changed&&this.data?.frames.length)next.frames=mergeFrames(this.data.frames,next.frames);
    this.data=next;this.data.live=live;this.$('.twin-start-hint').hidden=!!next.frames.length;this.$('.twin-follow').hidden=!live;this.$('.twin-run-id').textContent='运行 '+next.run_id;
    this.$('.twin-source').textContent=(live?'实时仿真':'已保存回放')+' · '+(next.fidelity==='state_only'?'旧记录 / 状态动作':'原始时序');
    const download=this.$('.twin-download');download.hidden=live;download.href='/api/twin/runs/'+encodeURIComponent(next.run_id)+'/download';download.textContent='回放数据';
    this.$('.twin-scrub input').max=String(Math.max(.01,next.duration_s));
    if(changed){this.sceneId=next.config?.task_kind||'belt';this.model=next.summary?.visual_profile||this.model;this.$('.twin-model').value=this.domain==='wind'?this.model:this.sceneId;this.rebuildModel();this.updateFeedButtons();}
    if(live&&this.followLive&&next.summary?.control_mode==='manual')this.time=next.duration_s;
    if(wasLive&&!live){this.followLive=false;this.time=next.summary?.control_mode==='manual'?next.duration_s:Math.min(this.time,next.duration_s);}
    this.updateUI(true);}
  async load(runId,{autoplay=true,queued=false}={}){if(!queued)this.clearQueue();const sequence=this.loadSequence=(this.loadSequence||0)+1;this.showError('');const response=await fetch('/api/twin/runs/'+encodeURIComponent(runId),{signal:this.abort.signal});const r=await response.json();if(!response.ok)throw Error(r.error||'回放未能读取');if(this.disposed||sequence!==this.loadSequence)return;this.setData(r,{autoplay,live:r.live});}
  clearQueue(){this.queue=[];this.queueIndex=0;this.$('.twin-queue')?.remove();}
  async runQueue(items){this.clearQueue();this.queue=items;this.queueIndex=0;this.$('.twin-toolbar').insertAdjacentHTML('afterend','<div class="twin-queue"><button data-twin="queue-prev">上一场</button><span></span><button data-twin="queue-next">下一场</button></div>');await this.playQueued(0);}
  async playQueued(index){if(this.queueBusy||!this.queue?.length)return;this.queueBusy=true;this.queueIndex=clamp(index,0,this.queue.length-1);try{const item=this.queue[this.queueIndex];await this.load(item.id,{autoplay:true,queued:true});this.$('.twin-queue span').textContent=(this.queueIndex+1)+' / '+this.queue.length+' · '+item.name;this.$('[data-twin=queue-prev]').disabled=this.queueIndex===0;this.$('[data-twin=queue-next]').disabled=this.queueIndex===this.queue.length-1;}catch(e){this.showError(e.message);}finally{this.queueBusy=false;}}
  async live(){if(this.liveBusy||this.disposed)return;this.liveBusy=true;try{const after=this.data?.live?this.data.frames.at(-1)?.time_s??-1:-1;const r=await fetch('/api/twin/live?after='+after,{signal:this.abort.signal});const data=await r.json();if(!r.ok)throw Error(data.error);if(!data.run_id)return;if(this.data?.run_id!==data.run_id&&after>=0){this.data=null;await this.load(data.run_id);return;}this.setData(data,{live:data.live,autoplay:true});if(!data.live&&this.manual){this.enableManual(false);this.host.dispatchEvent(new CustomEvent('twin:manual-ended',{bubbles:true,detail:data.run_id}));}}catch(e){if(e.name!=='AbortError')this.showError(e.message);}finally{this.liveBusy=false;}}
  bind(){const opts={signal:this.abort.signal};this.host.addEventListener('click',e=>{const b=e.target.closest('[data-twin]');if(!b)return;this.command(b.dataset.twin,b).catch(err=>this.showError(err.message));},opts);
    this.$('.twin-scrub input').addEventListener('input',e=>{this.time=Number(e.target.value);this.followLive=false;this.playing=false;this.updateUI(true);},opts);
    this.$('.twin-speed').addEventListener('change',e=>this.speed=Number(e.target.value),opts);
    this.$('.twin-camera').value=this.cameraMode;this.$('.twin-camera').addEventListener('change',e=>this.setCamera(e.target.value),opts);
    this.$('.twin-model').addEventListener('change',e=>{if(this.domain==='wind')this.model=e.target.value;else this.sceneId=e.target.value;this.rebuildModel();},opts);
    this.$('.twin-gamepad').addEventListener('change',e=>{this.gpEnabled=e.target.checked;this.stage.focus();},opts);
    this.stage.addEventListener('keydown',e=>{if(this.manual&&['KeyW','KeyA','KeyB','KeyC','KeyS','KeyD','KeyQ','KeyE','KeyJ','KeyL','Space'].includes(e.code)){e.preventDefault();if(!this.keys.has(e.code)&&this.domain==='ld'&&e.code==='Space')this.sendControl({feed:true,route:this.manualRoute||0});if(this.domain==='ld'&&['KeyA','KeyB','KeyC','KeyD'].includes(e.code)){const route=['KeyA','KeyB','KeyC','KeyD'].indexOf(e.code);if(route<2||this.sceneId==='barcode')this.manualRoute=route;}this.keys.add(e.code);}},opts);
    this.stage.addEventListener('keyup',e=>this.keys.delete(e.code),opts);
    this.stage.addEventListener('blur',()=>this.neutral(),opts);window.addEventListener('blur',()=>this.neutral(),opts);document.addEventListener('visibilitychange',()=>{if(document.hidden)this.neutral();},opts);
    const stick=this.$('.twin-stick');const handle=stick.querySelector('span');const move=e=>{const r=stick.getBoundingClientRect();this.pointer.x=clamp((e.clientX-r.left-r.width/2)/(r.width/2),-1,1);this.pointer.y=clamp((r.top+r.height/2-e.clientY)/(r.height/2),-1,1);handle.style.transform=`translate(${this.pointer.x*28}px,${-this.pointer.y*28}px)`;};
    stick.addEventListener('pointerdown',e=>{stick.setPointerCapture(e.pointerId);move(e);},opts);stick.addEventListener('pointermove',e=>{if(stick.hasPointerCapture(e.pointerId))move(e);},opts);for(const name of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(name,()=>{this.pointer={x:0,y:0};handle.style.transform='translate(0,0)';},opts);
    for(const [selector,key] of [['[data-twin=up]','KeyE'],['[data-twin=down]','KeyQ']]){const b=this.$(selector);if(!b)continue;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.keys.add(key);},opts);for(const n of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(n,()=>this.keys.delete(key),opts);}
    this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.renderer?.dispose();this.controls?.dispose();this.renderer=null;this.activateFallback();},opts);
  }
  neutral(){this.keys.clear();this.pointer={x:0,y:0};if(this.manual&&this.domain==='wind')this.sendControl({axes:[0,0,0,0]});}
  async sendControl(value){if(!this.manual||!this.onControl)return;try{await this.onControl(value);}catch(e){this.showError(e.message);}}
  updateFeedButtons(){if(this.domain==='ld'){this.$('.twin-manual>div:first-child>span').textContent=this.sceneId==='barcode'?'A / B / C / D 选择出口 · 空格单件上料':'A / B 选择出口 · 空格单件上料';this.$('.twin-feed').innerHTML=this.sceneId==='barcode'?['a','b','c','d'].map((k,i)=>`<button data-twin="feed-${k}">上料 ${i+1}</button>`).join(''):'<button data-twin="feed-a">上料 A</button><button data-twin="feed-b">上料 B</button>'; }}
  enableManual(on=true){this.manual=on;this.$('.twin-manual').hidden=!on;this.$('.twin-touch').hidden=!on;this.stage.focus();if(!on)this.neutral();}
  mapping(){this.$('.twin-manual').insertAdjacentHTML('beforeend',`<div class="twin-mapping">${['左右','前后','升降','朝向'].map((name,i)=>`<label>${name}<select data-axis="${i}" aria-label="${name}输入轴">${Array.from({length:16},(_,k)=>`<option value="${k}" ${k===(this.axesMap||[0,1,3,2])[i]?'selected':''}>轴 ${k}</option>`).join('')}</select><label><input type="checkbox" data-reverse="${i}" ${(this.axesReverse||[false,true,true,false])[i]?'checked':''}>反向</label></label>`).join('')}<label>回中死区<input data-deadzone type="number" aria-label="回中死区" min="0.02" max="0.5" step="0.01" value="${this.deadzone||.12}"></label><p>逐个拨动摇杆，检查下方输入值。航模 Mode 1 / Mode 2、自定义 HID 都可按实际通道重新映射。USB 设备须能被浏览器识别为游戏手柄。</p><button data-twin="save-mapping">保存通道</button></div>`);}
  async command(action,b){if(action==='play'){if(this.data&&this.time>=this.data.duration_s)this.time=0;this.playing=!this.playing;this.followLive=this.data?.live&&this.playing;this.updateUI(true);}
    else if(action==='restart'){this.time=0;this.followLive=false;this.playing=true;}
    else if(action==='queue-prev')await this.playQueued(this.queueIndex-1);
    else if(action==='queue-next')await this.playQueued(this.queueIndex+1);
    else if(action==='live'){this.followLive=true;this.playing=true;this.time=Math.max(0,(this.data?.duration_s||0)-.1);}
    else if(action==='fullscreen'){if(document.fullscreenElement)await document.exitFullscreen();else await this.host.requestFullscreen();}
    else if(action==='shot')this.snapshot();
    else if(action==='record')this.record();
    else if(action.startsWith('feed-'))await this.sendControl({feed:true,route:{'feed-a':0,'feed-b':1,'feed-c':2,'feed-d':3}[action]});
    else if(action==='mapping'){this.$('.twin-mapping')?.remove();this.mapping();}
    else if(action==='save-mapping'){this.axesMap=[...this.host.querySelectorAll('[data-axis]')].map(e=>Number(e.value));this.axesReverse=[...this.host.querySelectorAll('[data-reverse]')].map(e=>e.checked);this.deadzone=Number(this.$('[data-deadzone]').value);await this.savePreferences();this.$('.twin-mapping')?.remove();}
    else if(action==='event'){this.time=Number(b.dataset.time);this.playing=false;this.followLive=false;this.updateUI(true);}}
  saveBlob(blob,name){const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
  snapshot(){const canvas=this.renderer?this.canvas:this.$('.twin-fallback');canvas.toBlob(b=>{if(b)this.saveBlob(b,`scene-${this.data?.run_id||'preview'}-${this.time.toFixed(2)}s.png`);});}
  record(){if(this.recorder?.state==='recording'){this.recorder.stop();return;}if(!this.data?.frames.length)throw Error('请先运行一次仿真再录制动画');if(this.time>=this.data.duration_s)this.time=0;const c=this.renderer?this.canvas:this.$('.twin-fallback');if(!c.captureStream||!window.MediaRecorder)throw Error('当前浏览器不支持动画录制，请使用保存画面');
    const candidates=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'];const mime=candidates.find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error('当前浏览器没有可用的视频编码器');
    const stream=c.captureStream(24),parts=[];this.recordingStream=stream;this.recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2500000});this.recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};this.recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());this.recording=false;if(!this.disposed){this.$('[data-twin=record]').textContent='录制动画';this.saveBlob(new Blob(parts,{type:mime}),`animation-${this.data?.run_id||'preview'}.${mime.startsWith('video/mp4')?'mp4':'webm'}`);}};this.recorder.start(1000);this.recording=true;this.$('[data-twin=record]').textContent='停止录制';this.playing=true;clearTimeout(this.recordTimer);this.recordTimer=setTimeout(()=>{if(this.recorder.state==='recording')this.recorder.stop();},60000);}
  updateUI(force=false){if(!this.data)return;const f=atTime(this.data.frames,this.time,this.domain);if(!f)return;this.$('.twin-live').textContent=(this.data.live&&this.followLive?'实时 · ':'回放 · ')+label(f.state);this.$('.twin-live').dataset.fault=['FAULT','ABORTED'].includes(f.state)?'true':'false';this.$('.twin-clock').textContent=`${String(Math.floor(this.time/60)).padStart(2,'0')}:${(this.time%60).toFixed(2).padStart(5,'0')}`;
    const b=this.$('[data-twin=play]');b.textContent=this.playing?'Ⅱ':'▶';b.setAttribute('aria-label',this.playing?'暂停画面':'播放回放');this.$('.twin-scrub input').value=String(this.time);this.$('.twin-scrub span').textContent=fixed(this.time)+' / '+fixed(this.data.duration_s)+' s';
    const target=this.data.summary?.control_mode==='manual'?'手控':f.target_index>=(this.data.config?.waypoints?.length||0)?'返航点':'WP '+((f.target_index||0)+1);
    const values=this.domain==='wind'?[['高度',fixed(f.position[2]),'m'],['速度',fixed(f.speed),'m/s'],['电量',fixed(f.battery*100,1),'%'],['风速',fixed(f.wind_speed),'m/s'],['目标航点',target,''],['观测',f.sensor_valid?'正常':'中断','']]:[['当前物料',f.order_id??'—',''],['分流出口',this.sceneId==='barcode'?((f.destination??0)+1):(f.route===1?'B':'A'),''],['放行闸门',f.gate?'打开':'关闭',''],['确认完成',f.completed??0,'件'],['未知结果',f.unknown??0,'件'],['故障',f.fault==='NONE'?'无':f.fault||'无','']];
    this.$('.twin-values').innerHTML=values.map(([k,v,u])=>`<div><dt>${k}</dt><dd>${text(v)}<small>${u}</small></dd></div>`).join('');
    const events=this.data.events;const index=events.filter(e=>e.time_s<=this.time).length;const signature=index+':'+events.length;if(force||signature!==this.eventSignature){this.eventSignature=signature;const relevant=events.slice(Math.max(0,index-3),Math.min(events.length,index+4));this.$('.twin-events').innerHTML=relevant.map(e=>`<button data-twin="event" data-time="${e.time_s}" class="${e.time_s<=this.time?'past':''}"><span>${fixed(e.time_s)} s</span><strong>${text(label(e.code))}</strong><small>${text(e.detail)}</small></button>`).join('')||'<span>运行事件会在这里显示</span>';}}
  showError(message){const e=this.$('.twin-error');e.hidden=!message;e.textContent=message;}
  async readPreferences(){try{const response=await fetch('/api/manual/preferences',{signal:this.abort.signal});if(!response.ok)return;const p=await response.json();if(this.disposed)return;this.axesMap=p.axes;this.axesReverse=p.reverse;this.deadzone=p.deadzone;if(!this.data){this.model=p.model;this.$('.twin-model').value=this.domain==='wind'?this.model:this.sceneId;this.rebuildModel();this.updateFeedButtons();}}catch(e){if(e.name!=='AbortError')this.showError('遥控偏好未能读取');}}
  async savePreferences(){const r=await fetch('/api/manual/preferences',{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':this.csrf},body:JSON.stringify({axes:this.axesMap||[0,1,3,2],reverse:this.axesReverse||[false,true,true,false],deadzone:this.deadzone||.12,model:this.model})});const p=await r.json();if(!r.ok)throw Error(p.error||'遥控通道未能保存');}
  readGamepad(){if(!this.gpEnabled||!navigator.getGamepads)return null;const pads=navigator.getGamepads();const p=[...pads].find(p=>p?.connected);if(!p){this.$('.twin-controller').textContent='等待 USB 手柄；按一个按钮激活';return null;}const map=this.axesMap||[0,1,3,2],rev=this.axesReverse||[false,true,true,false];const axes=map.map((index,j)=>{let v=p.axes[index]||0;if(rev[j])v=-v;return Math.abs(v)<(this.deadzone||.12)?0:clamp(v,-1,1);});this.$('.twin-controller').textContent=p.id.slice(0,40)+' · '+p.axes.length+' 轴 · '+axes.map(v=>v.toFixed(2)).join(' / ');return axes;}
  controlsTick(now){if(!this.manual||document.hidden||now-this.lastInput<100)return;this.lastInput=now;
    const axes=this.readGamepad()||[this.pointer.x+(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),this.pointer.y+(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0),(this.keys.has('KeyE')?1:0)-(this.keys.has('KeyQ')?1:0),(this.keys.has('KeyL')?1:0)-(this.keys.has('KeyJ')?1:0)];
    if(this.domain==='wind')this.sendControl({axes:axes.map(v=>clamp(v,-1,1))});
    else if(this.gpEnabled){const p=[...navigator.getGamepads()].find(p=>p?.connected);const pressed=p?.buttons[0]?.pressed;if(pressed&&!this.lastFeed)this.sendControl({feed:true,route:this.sceneId==='barcode'&&p.buttons[3]?.pressed?3:this.sceneId==='barcode'&&p.buttons[2]?.pressed?2:p.buttons[1]?.pressed?1:0});this.lastFeed=pressed;}}
  loop(now){if(this.disposed)return;const dt=Math.min(.1,Math.max(0,(now-(this.lastRAF??now))/1000));this.lastRAF=now;
    if(this.data?.frames.length){if(this.playing){this.time=clamp(this.time+dt*this.speed,0,this.data.duration_s);if(this.time>=this.data.duration_s&&!this.data.live){this.playing=false;if(this.queue?.length&&this.queueIndex<this.queue.length-1)this.playQueued(this.queueIndex+1);}}
      const f=atTime(this.data.frames,this.time,this.domain);if(this.renderer){this.modelObject.update(f,this.time,this.data.frames);const m=this.modelObject;if(this.cameraMode==='follow'){const offset=this.domain==='wind'?new T.Vector3(5,3,6):new T.Vector3(3,2.4,4);this.camera.position.lerp(m.tracked.clone().add(offset),.08);this.controls.target.lerp(m.tracked,.12);}else if(this.cameraMode==='cinematic'){const a=this.domain==='wind'?this.time*.027:this.time*.03;const home=new T.Vector3(...m.home);const target=m.target;this.camera.position.set(target.x+Math.cos(a)*home.x+Math.sin(a)*home.z,home.y,target.z-Math.sin(a)*home.x+Math.cos(a)*home.z);this.controls.target.copy(target);}this.controls.update();}
      else this.drawFallback(f);
      if(now-this.lastUI>100){this.updateUI();this.lastUI=now;}}
    if(this.renderer){this.controls.update();this.renderer.render(this.scene,this.camera);}if(this.recording&&!this.data?.live&&this.data?.frames.length&&this.time>=this.data.duration_s)this.recorder?.stop();this.controlsTick(now);this.raf=requestAnimationFrame(t=>this.loop(t));}
  drawFallback(f){const c=this.$('.twin-fallback'),g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#10202d';g.fillRect(0,0,w,h);g.strokeStyle='#284353';for(let x=0;x<w;x+=40){g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke();}g.fillStyle='#49d4c0';
    if(this.domain==='ld'){g.fillStyle='#40576b';g.fillRect(w*.12,h*.38,w*.6,h*.16);g.strokeStyle='#a3b6c2';g.lineWidth=16;for(const sy of [-1,1]){g.beginPath();g.moveTo(w*.7,h*.46);g.lineTo(w*.9,h*(.46+sy*.2));g.stroke();}if(f.order_id!=null&&f.progress!=null){const p=sorterPosition(f.progress,f.physical_route??f.route);g.fillStyle='#e8b56c';g.fillRect(w*(.15+(p[0]+2.6)/5.4*.74),h*(.46+p[2]*.14)-12,24,24);}g.fillStyle=f.gate?'#55d8b5':'#e6ae5a';g.fillRect(w*.24,h*.32,10,h*.27);}
    else{const rows=this.data.frames;let max=10;for(const p of rows)max=Math.max(max,Math.abs(p.position[0]),Math.abs(p.position[1]));const px=x=>w*.5+x/max*w*.34,py=y=>h*.55-y/max*h*.35;g.strokeStyle='#43d9c2';g.lineWidth=3;g.beginPath();for(let i=0;i<=f.index;i++){const p=rows[i].position;if(i===0)g.moveTo(px(p[0]),py(p[1]));else g.lineTo(px(p[0]),py(p[1]));}g.stroke();const [x,y]=f.position;g.fillStyle='#b4e6ec';g.fillRect(px(x)-10,py(y)-8,20,16);g.strokeStyle='#b4e6ec';for(const sx of [-1,1])for(const sy of [-1,1]){g.beginPath();g.moveTo(px(x),py(y));g.lineTo(px(x)+sx*22,py(y)+sy*19);g.stroke();g.beginPath();g.arc(px(x)+sx*22,py(y)+sy*19,9,0,Math.PI*2);g.stroke();}}
    g.fillStyle='#dbeaf0';g.font=Math.round(w/48)+'px Segoe UI';g.fillText(label(f.state)+' · '+this.time.toFixed(2)+' s',24,40);}
  dispose(){if(this.disposed)return;this.neutral();this.disposed=true;this.abort.abort();cancelAnimationFrame(this.raf);clearTimeout(this.recordTimer);if(this.recorder?.state==='recording')this.recorder.stop();this.recordingStream?.getTracks().forEach(t=>t.stop());this.resizeObserver?.disconnect();this.controls?.dispose();if(this.scene)disposeScene(this.scene);this.renderer?.dispose();}
}
